import fs from 'fs';
import path from 'path';

const CATEGORIES = [
  "Chatbots & Companions", "Coding & Development", "Enterprise Search", "Productivity & Workflows",
  "Video Generation", "Image Generation", "Music & Audio", "Meeting Assistants", "Graphic Design",
  "Voice Generation", "App & Website Builders", "Legal Tech", "Healthcare", "Finance & Accounting",
  "HR & Recruiting", "Sales & CRM", "Content Marketing", "Data Analysis", "Customer Support",
  "Education", "Research", "Copywriting", "SEO", "Social Media", "Email Marketing",
  "Business Strategy", "Project Management", "Brainstorming", "Personal Growth", "Gaming",
  "Cybersecurity", "DevOps", "Testing", "Translation", "3D Generation", "Robotics",
  "Agriculture", "Real Estate", "Logistics", "Manufacturing"
];

// Seed names
const prefixes = ["Auto", "Neuro", "Synapse", "Quantum", "Cyber", "Aura", "Nexus", "Hyper", "Meta", "Omni", "Core", "Brain", "Mind", "Deep", "Alpha", "Nova", "Pulse", "Echo", "Lumina", "Vertex", "Logic", "Vision", "Spark", "Flow", "Synthetix", "Gen", "Next", "Pro", "Smart", "Wise", "Data", "Tech", "Cloud", "Grid", "Matrix", "Sphere", "Wave", "Link", "Sync", "Bot"];
const suffixes = ["GPT", "AI", "Mind", "Bot", "Brain", "Gen", "Logic", "Base", "Hub", "Node", "Core", "Link", "Sync", "Wave", "Sphere", "Grid", "Matrix", "Cloud", "Tech", "Data", "Wise", "Smart", "Pro", "Next", "Gen", "Synthetix", "Flow", "Spark", "Vision", "Vertex", "Lumina", "Echo", "Pulse", "Nova", "Alpha", "Deep", "Omni", "Meta", "Hyper", "Nexus"];

const vendors = ["OpenAI", "Anthropic", "Google", "Microsoft", "Meta", "IBM", "AWS", "HuggingFace", "Stability AI", "Midjourney", "Perplexity", "Cohere", "AI21", "Inflection", "Mistral", "xAI", "Baidu", "Tencent", "Alibaba", "ByteDance", "Nvidia", "Apple", "Salesforce", "Oracle", "SAP", "Adobe", "Autodesk", "Canva", "Notion", "Slack"];

function generateTool(index) {
  const isReal = index < 20; // Ensure some real tools are kept at top
  const category = CATEGORIES[index % CATEGORIES.length];
  
  let name, vendor, url, price, score, color;
  
  if (isReal && index === 0) { name = "ChatGPT"; vendor = "OpenAI"; url = "https://chat.openai.com"; price = "Freemium / $20/mo"; score = 98.9; color = "oklch(0.6 0.15 160)"; }
  else if (isReal && index === 1) { name = "Claude"; vendor = "Anthropic"; url = "https://claude.ai"; price = "Freemium / $20/mo"; score = 97.5; color = "oklch(0.7 0.15 45)"; }
  else if (isReal && index === 2) { name = "Midjourney"; vendor = "Midjourney"; url = "https://midjourney.com"; price = "$10/mo"; score = 95.0; color = "oklch(0.6 0.2 300)"; }
  else if (isReal && index === 3) { name = "Cursor"; vendor = "Anysphere"; url = "https://cursor.com"; price = "Freemium / $20/mo"; score = 96.8; color = "oklch(0.8 0.1 252)"; }
  else if (isReal && index === 4) { name = "Perplexity"; vendor = "Perplexity AI"; url = "https://perplexity.ai"; price = "Freemium / $20/mo"; score = 95.2; color = "oklch(0.6 0.1 200)"; }
  else {
    name = `${prefixes[Math.floor(Math.random() * prefixes.length)]}${suffixes[Math.floor(Math.random() * suffixes.length)]} ${Math.floor(Math.random() * 10) || ''}`.trim();
    vendor = vendors[Math.floor(Math.random() * vendors.length)];
    // Randomly miss URL for 10% of tools
    url = Math.random() > 0.9 ? "" : `https://${name.toLowerCase().replace(/[^a-z0-9]/g, '')}.com`;
    price = Math.random() > 0.7 ? "Free" : (Math.random() > 0.5 ? "$20/mo" : "Enterprise");
    score = Math.floor(Math.random() * 300 + 700) / 10; // 70.0 - 99.9
    color = `oklch(0.${Math.floor(Math.random() * 5 + 4)} 0.${Math.floor(Math.random() * 2 + 1)} ${Math.floor(Math.random() * 360)})`;
  }

  return { name, category, score, price, vendor, color, website_url: url };
}

function generateAgent(index) {
  const category = CATEGORIES[index % CATEGORIES.length];
  const name = `${prefixes[Math.floor(Math.random() * prefixes.length)]} Agent ${index}`;
  const vendor = vendors[Math.floor(Math.random() * vendors.length)];
  const url = Math.random() > 0.9 ? "" : `https://${name.toLowerCase().replace(/[^a-z0-9]/g, '')}.com`;
  
  return {
    name,
    cat: category,
    score: Math.floor(Math.random() * 20 + 80) / 10, // 8.0 - 9.9
    pricing: Math.random() > 0.6 ? "Free" : (Math.random() > 0.5 ? "Freemium" : "Enterprise"),
    vendor,
    color: `oklch(0.${Math.floor(Math.random() * 5 + 4)} 0.${Math.floor(Math.random() * 2 + 1)} ${Math.floor(Math.random() * 360)})`,
    url,
    desc: `An autonomous AI agent designed for ${category.toLowerCase()} tasks.`
  };
}

const tools = Array.from({ length: 400 }, (_, i) => generateTool(i));
// Ensure unique names
const uniqueTools = Array.from(new Map(tools.map(t => [t.name, t])).values());

const agents = Array.from({ length: 400 }, (_, i) => generateAgent(i));

const toolsContent = `// Auto-generated by scripts/generate-data.ts

export const CATEGORIES = ${JSON.stringify(CATEGORIES, null, 2)};

export const COMPARE_METRICS = [
  "Price", "Coding", "Reasoning", "Research", "Speed", "Context", "Ease of Use", "Integration", "Accuracy", "Support"
];

export const AI_TOOLS = ${JSON.stringify(uniqueTools, null, 2)};
`;

const agentsContent = `// Auto-generated by scripts/generate-data.ts

export const AI_AGENTS = ${JSON.stringify(agents, null, 2)};
`;

fs.writeFileSync(path.join(process.cwd(), 'src/lib/data/tools.ts'), toolsContent);
fs.writeFileSync(path.join(process.cwd(), 'src/lib/data/agents.ts'), agentsContent);
console.log("Successfully generated tools and agents!");
