import fs from "fs";
import path from "path";

async function checkUrl(url: string): Promise<boolean> {
  if (!url) return false;
  try {
    const controller = new AbortController();
    const timeout = setTimeout(() => controller.abort(), 2000);
    // Simple HEAD request to check reachability
    const res = await fetch(url, { 
      method: 'HEAD', 
      signal: controller.signal,
      headers: {
        'User-Agent': 'Mozilla/5.0 (compatible; OptimaBot/1.0)'
      }
    });
    clearTimeout(timeout);
    return res.ok || res.status < 500; // Anything not a 5xx or error is considered "reachable"
  } catch (err) {
    return false; // ENOTFOUND, Timeout, etc.
  }
}

async function verifyTools() {
  const toolsPath = path.resolve(process.cwd(), "src/lib/data/tools.ts");
  const content = fs.readFileSync(toolsPath, "utf-8");
  
  // Extract JSON array from the file
  const jsonMatch = content.match(/export const AI_TOOLS = (\[[\s\S]*?\]);/);
  if (!jsonMatch) {
    console.error("Could not find AI_TOOLS array in file");
    return;
  }
  
  let tools;
  try {
    tools = eval(jsonMatch[1]);
  } catch (err) {
    console.error("Failed to parse AI_TOOLS:", err);
    return;
  }
  console.log(`Checking ${tools.length} tools...`);
  
  // To speed it up, we can check in batches or Promise.all, but we should limit concurrency
  // Actually, since these are mostly fake domains, DNS will resolve them to ENOTFOUND very quickly.
  // We will do 50 at a time.
  const batchSize = 50;
  for (let i = 0; i < tools.length; i += batchSize) {
    const batch = tools.slice(i, i + batchSize);
    await Promise.all(batch.map(async (tool: any) => {
      if (tool.website_url) {
        const isReachable = await checkUrl(tool.website_url);
        if (!isReachable) {
          tool.website_url = ""; // Clear URL if not reachable
        }
      }
    }));
    console.log(`Processed ${Math.min(i + batchSize, tools.length)} / ${tools.length}`);
  }
  
  const updatedContent = `// Auto-generated by scripts/generate-data.ts\n\nexport const AI_TOOLS = ${JSON.stringify(tools, null, 2)};\n`;
  fs.writeFileSync(toolsPath, updatedContent, "utf-8");
  console.log("tools.ts updated successfully.");
}

verifyTools().catch(console.error);
