// Auto-generated by scripts/generate-data.ts

export const CATEGORIES = [
  "Chatbots & Companions",
  "Coding & Development",
  "Enterprise Search",
  "Productivity & Workflows",
  "Video Generation",
  "Image Generation",
  "Music & Audio",
  "Meeting Assistants",
  "Graphic Design",
  "Voice Generation",
  "App & Website Builders",
  "Legal Tech",
  "Marketing & Sales",
  "Research",
  "Finance",
  "Education",
  "Healthcare",
  "Data Analysis",
  "Customer Support",
  "Writing",
  "Translation",
  "Gaming",
  "3D Generation",
  "Robotics",
  "Agriculture",
  "Real Estate",
  "Logistics",
  "Manufacturing"
];

export const COMPARE_METRICS = [
  "Price", "Coding", "Reasoning", "Research", "Speed", "Context", "Ease of Use", "Integration", "Accuracy", "Support"
];
export const AI_TOOLS = [
  {
    "name": "New AI Tool 380",
    "category": "AI Agents",
    "score": 95,
    "price": "Free",
    "vendor": "NextGen AI",
    "color": "oklch(0.7 0.15 220)"
  },
  {
    "name": "ChatGPT",
    "category": "Chatbots & Companions",
    "score": 98.9,
    "price": "Freemium / $20/mo",
    "vendor": "OpenAI",
    "color": "oklch(0.6 0.15 160)",
    "website_url": ""
  },
  {
    "name": "Claude",
    "category": "Coding & Development",
    "score": 97.5,
    "price": "Freemium / $20/mo",
    "vendor": "Anthropic",
    "color": "oklch(0.7 0.15 45)",
    "website_url": "https://claude.ai"
  },
  {
    "name": "Midjourney",
    "category": "Enterprise Search",
    "score": 95,
    "price": "$10/mo",
    "vendor": "Midjourney",
    "color": "oklch(0.6 0.2 300)",
    "website_url": "https://midjourney.com"
  },
  {
    "name": "Cursor",
    "category": "Productivity & Workflows",
    "score": 96.8,
    "price": "Freemium / $20/mo",
    "vendor": "Anysphere",
    "color": "oklch(0.8 0.1 252)",
    "website_url": "https://cursor.com"
  },
  {
    "name": "Perplexity",
    "category": "Video Generation",
    "score": 95.2,
    "price": "Freemium / $20/mo",
    "vendor": "Perplexity AI",
    "color": "oklch(0.6 0.1 200)",
    "website_url": ""
  },
  {
    "name": "GenSync 4",
    "category": "Image Generation",
    "score": 95.6,
    "price": "$20/mo",
    "vendor": "Cohere",
    "color": "oklch(0.5 0.1 55)",
    "website_url": ""
  },
  {
    "name": "AutoLogic 1",
    "category": "Music & Audio",
    "score": 88.2,
    "price": "$20/mo",
    "vendor": "Notion",
    "color": "oklch(0.6 0.2 57)",
    "website_url": ""
  },
  {
    "name": "SmartData",
    "category": "Meeting Assistants",
    "score": 75.1,
    "price": "Enterprise",
    "vendor": "AI21",
    "color": "oklch(0.6 0.2 101)",
    "website_url": ""
  },
  {
    "name": "QuantumLogic 6",
    "category": "Graphic Design",
    "score": 99,
    "price": "Enterprise",
    "vendor": "Mistral",
    "color": "oklch(0.4 0.2 309)",
    "website_url": ""
  },
  {
    "name": "EchoData",
    "category": "Voice Generation",
    "score": 90.7,
    "price": "Free",
    "vendor": "HuggingFace",
    "color": "oklch(0.8 0.2 260)",
    "website_url": ""
  },
  {
    "name": "SmartWave 7",
    "category": "App & Website Builders",
    "score": 78.4,
    "price": "Enterprise",
    "vendor": "Anthropic",
    "color": "oklch(0.5 0.2 314)",
    "website_url": ""
  },
  {
    "name": "SparkBase",
    "category": "Legal Tech",
    "score": 95.1,
    "price": "$20/mo",
    "vendor": "xAI",
    "color": "oklch(0.4 0.2 196)",
    "website_url": ""
  },
  {
    "name": "DeepSmart 9",
    "category": "Healthcare",
    "score": 81.8,
    "price": "$20/mo",
    "vendor": "Perplexity",
    "color": "oklch(0.4 0.1 230)",
    "website_url": ""
  },
  {
    "name": "NextFlow 7",
    "category": "Brainstorming",
    "score": 99.8,
    "price": "Enterprise",
    "vendor": "Apple",
    "color": "oklch(0.7 0.2 144)",
    "website_url": ""
  },
  {
    "name": "ProData",
    "category": "HR & Recruiting",
    "score": 83.5,
    "price": "Free",
    "vendor": "AWS",
    "color": "oklch(0.8 0.2 273)",
    "website_url": ""
  },
  {
    "name": "BotLink 1",
    "category": "Sales & CRM",
    "score": 93.3,
    "price": "$20/mo",
    "vendor": "Nvidia",
    "color": "oklch(0.8 0.1 207)",
    "website_url": ""
  },
  {
    "name": "GenGen 1",
    "category": "Content Marketing",
    "score": 81.9,
    "price": "$20/mo",
    "vendor": "ByteDance",
    "color": "oklch(0.4 0.2 200)",
    "website_url": ""
  },
  {
    "name": "PulseBot 7",
    "category": "Data Analysis",
    "score": 88.8,
    "price": "$20/mo",
    "vendor": "Adobe",
    "color": "oklch(0.4 0.1 222)",
    "website_url": ""
  },
  {
    "name": "ProAlpha 2",
    "category": "Customer Support",
    "score": 76.3,
    "price": "Enterprise",
    "vendor": "Anthropic",
    "color": "oklch(0.8 0.2 224)",
    "website_url": ""
  },
  {
    "name": "GenTech 6",
    "category": "Education",
    "score": 82.7,
    "price": "$20/mo",
    "vendor": "Perplexity",
    "color": "oklch(0.7 0.1 70)",
    "website_url": ""
  },
  {
    "name": "WiseAI 2",
    "category": "Research",
    "score": 93.6,
    "price": "Enterprise",
    "vendor": "Inflection",
    "color": "oklch(0.8 0.2 287)",
    "website_url": ""
  },
  {
    "name": "DeepDeep 9",
    "category": "Copywriting",
    "score": 88.4,
    "price": "$20/mo",
    "vendor": "Mistral",
    "color": "oklch(0.7 0.2 344)",
    "website_url": ""
  },
  {
    "name": "GenHub 8",
    "category": "SEO",
    "score": 97.1,
    "price": "Free",
    "vendor": "ByteDance",
    "color": "oklch(0.4 0.1 238)",
    "website_url": ""
  },
  {
    "name": "AutoAlpha 5",
    "category": "Social Media",
    "score": 98.6,
    "price": "$20/mo",
    "vendor": "Slack",
    "color": "oklch(0.8 0.1 126)",
    "website_url": ""
  },
  {
    "name": "CloudBase 9",
    "category": "Email Marketing",
    "score": 83.4,
    "price": "Free",
    "vendor": "Anthropic",
    "color": "oklch(0.6 0.2 342)",
    "website_url": ""
  },
  {
    "name": "EchoHyper 9",
    "category": "Business Strategy",
    "score": 73.7,
    "price": "$20/mo",
    "vendor": "Apple",
    "color": "oklch(0.4 0.2 285)",
    "website_url": ""
  },
  {
    "name": "CyberNext 4",
    "category": "Project Management",
    "score": 81.6,
    "price": "Free",
    "vendor": "Anthropic",
    "color": "oklch(0.8 0.2 318)",
    "website_url": ""
  },
  {
    "name": "AutoVertex 5",
    "category": "Brainstorming",
    "score": 77.3,
    "price": "$20/mo",
    "vendor": "Salesforce",
    "color": "oklch(0.6 0.2 69)",
    "website_url": ""
  },
  {
    "name": "NovaMind",
    "category": "Personal Growth",
    "score": 77.9,
    "price": "Free",
    "vendor": "AWS",
    "color": "oklch(0.8 0.1 280)",
    "website_url": ""
  },
  {
    "name": "SynapseNode 8",
    "category": "Gaming",
    "score": 81.2,
    "price": "$20/mo",
    "vendor": "Nvidia",
    "color": "oklch(0.4 0.1 89)",
    "website_url": ""
  },
  {
    "name": "QuantumBot 2",
    "category": "Cybersecurity",
    "score": 74.2,
    "price": "$20/mo",
    "vendor": "Perplexity",
    "color": "oklch(0.4 0.1 38)",
    "website_url": ""
  },
  {
    "name": "SmartHyper 1",
    "category": "DevOps",
    "score": 84.7,
    "price": "Free",
    "vendor": "Oracle",
    "color": "oklch(0.5 0.2 79)",
    "website_url": ""
  },
  {
    "name": "OmniGrid 9",
    "category": "Testing",
    "score": 76.8,
    "price": "$20/mo",
    "vendor": "Oracle",
    "color": "oklch(0.6 0.1 51)",
    "website_url": ""
  },
  {
    "name": "GridMind 6",
    "category": "Translation",
    "score": 80.2,
    "price": "Free",
    "vendor": "Autodesk",
    "color": "oklch(0.7 0.1 216)",
    "website_url": ""
  },
  {
    "name": "SynapseBot 6",
    "category": "3D Generation",
    "score": 89.5,
    "price": "Enterprise",
    "vendor": "Apple",
    "color": "oklch(0.8 0.2 125)",
    "website_url": ""
  },
  {
    "name": "BrainCloud",
    "category": "Robotics",
    "score": 79.4,
    "price": "Free",
    "vendor": "Slack",
    "color": "oklch(0.5 0.1 35)",
    "website_url": ""
  },
  {
    "name": "HyperLink 7",
    "category": "Agriculture",
    "score": 70.4,
    "price": "Enterprise",
    "vendor": "Salesforce",
    "color": "oklch(0.7 0.2 26)",
    "website_url": ""
  },
  {
    "name": "DeepDeep 7",
    "category": "Graphic Design",
    "score": 96.2,
    "price": "Enterprise",
    "vendor": "IBM",
    "color": "oklch(0.6 0.2 12)",
    "website_url": ""
  },
  {
    "name": "LinkSpark 2",
    "category": "Logistics",
    "score": 74.8,
    "price": "$20/mo",
    "vendor": "HuggingFace",
    "color": "oklch(0.4 0.2 177)",
    "website_url": ""
  },
  {
    "name": "NeuroCore 9",
    "category": "Manufacturing",
    "score": 78.1,
    "price": "$20/mo",
    "vendor": "Nvidia",
    "color": "oklch(0.6 0.2 34)",
    "website_url": ""
  },
  {
    "name": "SynthetixBrain 9",
    "category": "Chatbots & Companions",
    "score": 91.2,
    "price": "Free",
    "vendor": "Canva",
    "color": "oklch(0.6 0.2 173)",
    "website_url": ""
  },
  {
    "name": "SparkFlow",
    "category": "Coding & Development",
    "score": 72.4,
    "price": "Free",
    "vendor": "Notion",
    "color": "oklch(0.5 0.1 204)",
    "website_url": ""
  },
  {
    "name": "WaveHub 3",
    "category": "Enterprise Search",
    "score": 70.6,
    "price": "$20/mo",
    "vendor": "xAI",
    "color": "oklch(0.5 0.1 278)",
    "website_url": ""
  },
  {
    "name": "NovaLumina 6",
    "category": "App & Website Builders",
    "score": 87.6,
    "price": "$20/mo",
    "vendor": "OpenAI",
    "color": "oklch(0.8 0.2 209)",
    "website_url": ""
  },
  {
    "name": "VisionLogic 2",
    "category": "Video Generation",
    "score": 88.6,
    "price": "Enterprise",
    "vendor": "IBM",
    "color": "oklch(0.8 0.1 30)",
    "website_url": ""
  },
  {
    "name": "VisionLogic",
    "category": "Image Generation",
    "score": 93,
    "price": "Free",
    "vendor": "Oracle",
    "color": "oklch(0.7 0.2 316)",
    "website_url": ""
  },
  {
    "name": "WiseWise 8",
    "category": "Music & Audio",
    "score": 97.4,
    "price": "Free",
    "vendor": "Cohere",
    "color": "oklch(0.8 0.2 309)",
    "website_url": ""
  },
  {
    "name": "CoreTech 9",
    "category": "Meeting Assistants",
    "score": 81.9,
    "price": "$20/mo",
    "vendor": "Perplexity",
    "color": "oklch(0.6 0.2 254)",
    "website_url": ""
  },
  {
    "name": "LinkPro",
    "category": "Voice Generation",
    "score": 83.1,
    "price": "Free",
    "vendor": "AI21",
    "color": "oklch(0.6 0.1 220)",
    "website_url": ""
  },
  {
    "name": "GenNexus 9",
    "category": "App & Website Builders",
    "score": 77.9,
    "price": "Enterprise",
    "vendor": "Alibaba",
    "color": "oklch(0.7 0.1 191)",
    "website_url": ""
  },
  {
    "name": "TechMind 6",
    "category": "Legal Tech",
    "score": 70.6,
    "price": "Free",
    "vendor": "Nvidia",
    "color": "oklch(0.5 0.1 101)",
    "website_url": ""
  },
  {
    "name": "EchoLink 3",
    "category": "Healthcare",
    "score": 86.7,
    "price": "Free",
    "vendor": "Notion",
    "color": "oklch(0.7 0.1 269)",
    "website_url": ""
  },
  {
    "name": "NextHub 2",
    "category": "Finance & Accounting",
    "score": 81,
    "price": "Free",
    "vendor": "Alibaba",
    "color": "oklch(0.5 0.2 73)",
    "website_url": ""
  },
  {
    "name": "SmartVertex 6",
    "category": "HR & Recruiting",
    "score": 72.2,
    "price": "$20/mo",
    "vendor": "Salesforce",
    "color": "oklch(0.8 0.1 253)",
    "website_url": ""
  },
  {
    "name": "CyberCloud 8",
    "category": "Sales & CRM",
    "score": 99.2,
    "price": "$20/mo",
    "vendor": "Meta",
    "color": "oklch(0.7 0.2 250)",
    "website_url": ""
  },
  {
    "name": "DataEcho 2",
    "category": "Content Marketing",
    "score": 74.9,
    "price": "Enterprise",
    "vendor": "OpenAI",
    "color": "oklch(0.4 0.2 331)",
    "website_url": ""
  },
  {
    "name": "LogicLink 2",
    "category": "Data Analysis",
    "score": 84.4,
    "price": "Enterprise",
    "vendor": "OpenAI",
    "color": "oklch(0.7 0.2 38)",
    "website_url": ""
  },
  {
    "name": "GridHub 9",
    "category": "Customer Support",
    "score": 70.7,
    "price": "Free",
    "vendor": "Apple",
    "color": "oklch(0.4 0.2 2)",
    "website_url": ""
  },
  {
    "name": "MetaMeta 1",
    "category": "Education",
    "score": 80.5,
    "price": "$20/mo",
    "vendor": "IBM",
    "color": "oklch(0.5 0.2 296)",
    "website_url": ""
  },
  {
    "name": "TechSync 1",
    "category": "Research",
    "score": 98.9,
    "price": "Free",
    "vendor": "Baidu",
    "color": "oklch(0.6 0.2 181)",
    "website_url": ""
  },
  {
    "name": "AlphaDeep 6",
    "category": "Copywriting",
    "score": 92.6,
    "price": "$20/mo",
    "vendor": "Stability AI",
    "color": "oklch(0.8 0.1 331)",
    "website_url": ""
  },
  {
    "name": "GenCore 1",
    "category": "SEO",
    "score": 81.9,
    "price": "Free",
    "vendor": "Microsoft",
    "color": "oklch(0.4 0.1 36)",
    "website_url": ""
  },
  {
    "name": "CyberPulse 1",
    "category": "Social Media",
    "score": 80.5,
    "price": "Enterprise",
    "vendor": "Microsoft",
    "color": "oklch(0.7 0.2 48)",
    "website_url": ""
  },
  {
    "name": "LuminaOmni 2",
    "category": "Email Marketing",
    "score": 79.7,
    "price": "Free",
    "vendor": "Anthropic",
    "color": "oklch(0.7 0.2 332)",
    "website_url": ""
  },
  {
    "name": "WiseBrain 5",
    "category": "Business Strategy",
    "score": 87.1,
    "price": "$20/mo",
    "vendor": "Apple",
    "color": "oklch(0.4 0.1 206)",
    "website_url": ""
  },
  {
    "name": "NeuroPro 9",
    "category": "Coding & Development",
    "score": 73.7,
    "price": "Enterprise",
    "vendor": "Perplexity",
    "color": "oklch(0.5 0.1 89)",
    "website_url": ""
  },
  {
    "name": "OmniCloud 2",
    "category": "Brainstorming",
    "score": 98.6,
    "price": "Enterprise",
    "vendor": "Cohere",
    "color": "oklch(0.7 0.1 326)",
    "website_url": ""
  },
  {
    "name": "LinkOmni 4",
    "category": "Personal Growth",
    "score": 78.3,
    "price": "$20/mo",
    "vendor": "Inflection",
    "color": "oklch(0.8 0.2 289)",
    "website_url": ""
  },
  {
    "name": "VertexMeta 2",
    "category": "Gaming",
    "score": 91.8,
    "price": "Free",
    "vendor": "Slack",
    "color": "oklch(0.5 0.2 58)",
    "website_url": ""
  },
  {
    "name": "LinkSynthetix 1",
    "category": "Cybersecurity",
    "score": 77.1,
    "price": "$20/mo",
    "vendor": "Apple",
    "color": "oklch(0.8 0.1 58)",
    "website_url": ""
  },
  {
    "name": "DataMatrix 6",
    "category": "DevOps",
    "score": 97,
    "price": "Free",
    "vendor": "Adobe",
    "color": "oklch(0.6 0.2 170)",
    "website_url": ""
  },
  {
    "name": "SphereCloud 5",
    "category": "Testing",
    "score": 88.2,
    "price": "Free",
    "vendor": "Meta",
    "color": "oklch(0.5 0.1 133)",
    "website_url": ""
  },
  {
    "name": "CyberAlpha 3",
    "category": "Translation",
    "score": 92.2,
    "price": "Free",
    "vendor": "Oracle",
    "color": "oklch(0.8 0.2 298)",
    "website_url": ""
  },
  {
    "name": "AuraMeta 1",
    "category": "3D Generation",
    "score": 72.8,
    "price": "$20/mo",
    "vendor": "ByteDance",
    "color": "oklch(0.8 0.2 341)",
    "website_url": ""
  },
  {
    "name": "OmniSmart 9",
    "category": "Robotics",
    "score": 76.6,
    "price": "Enterprise",
    "vendor": "Canva",
    "color": "oklch(0.6 0.1 140)",
    "website_url": ""
  },
  {
    "name": "NextMind 6",
    "category": "Agriculture",
    "score": 83.9,
    "price": "Free",
    "vendor": "Stability AI",
    "color": "oklch(0.8 0.1 278)",
    "website_url": ""
  },
  {
    "name": "LuminaPro 4",
    "category": "Real Estate",
    "score": 71.4,
    "price": "Free",
    "vendor": "SAP",
    "color": "oklch(0.8 0.1 339)",
    "website_url": ""
  },
  {
    "name": "NeuroGPT 6",
    "category": "Logistics",
    "score": 88.2,
    "price": "$20/mo",
    "vendor": "Anthropic",
    "color": "oklch(0.4 0.1 214)",
    "website_url": ""
  },
  {
    "name": "AlphaWave 4",
    "category": "Manufacturing",
    "score": 85.2,
    "price": "Enterprise",
    "vendor": "HuggingFace",
    "color": "oklch(0.8 0.1 214)",
    "website_url": ""
  },
  {
    "name": "QuantumGen 4",
    "category": "Chatbots & Companions",
    "score": 72.6,
    "price": "$20/mo",
    "vendor": "Perplexity",
    "color": "oklch(0.7 0.2 68)",
    "website_url": ""
  },
  {
    "name": "SparkGen 4",
    "category": "Coding & Development",
    "score": 75.2,
    "price": "Enterprise",
    "vendor": "Cohere",
    "color": "oklch(0.8 0.1 215)",
    "website_url": ""
  },
  {
    "name": "MindNexus 6",
    "category": "Enterprise Search",
    "score": 89.6,
    "price": "$20/mo",
    "vendor": "Adobe",
    "color": "oklch(0.5 0.2 32)",
    "website_url": ""
  },
  {
    "name": "WiseMeta 8",
    "category": "Productivity & Workflows",
    "score": 86.4,
    "price": "Free",
    "vendor": "SAP",
    "color": "oklch(0.5 0.1 2)",
    "website_url": ""
  },
  {
    "name": "DeepGen 5",
    "category": "Video Generation",
    "score": 89.6,
    "price": "$20/mo",
    "vendor": "AI21",
    "color": "oklch(0.6 0.2 329)",
    "website_url": ""
  },
  {
    "name": "CyberOmni 3",
    "category": "Image Generation",
    "score": 81.8,
    "price": "$20/mo",
    "vendor": "xAI",
    "color": "oklch(0.6 0.1 87)",
    "website_url": ""
  },
  {
    "name": "NexusAlpha 4",
    "category": "Music & Audio",
    "score": 98.5,
    "price": "Enterprise",
    "vendor": "Mistral",
    "color": "oklch(0.8 0.1 107)",
    "website_url": ""
  },
  {
    "name": "LinkHub 2",
    "category": "Meeting Assistants",
    "score": 88.3,
    "price": "$20/mo",
    "vendor": "Salesforce",
    "color": "oklch(0.7 0.1 165)",
    "website_url": ""
  },
  {
    "name": "DataVertex 6",
    "category": "Graphic Design",
    "score": 71.3,
    "price": "Enterprise",
    "vendor": "Notion",
    "color": "oklch(0.5 0.2 339)",
    "website_url": ""
  },
  {
    "name": "SyncHyper 3",
    "category": "Voice Generation",
    "score": 72.1,
    "price": "Free",
    "vendor": "Inflection",
    "color": "oklch(0.6 0.1 38)",
    "website_url": ""
  },
  {
    "name": "ProLumina 9",
    "category": "App & Website Builders",
    "score": 78.1,
    "price": "Enterprise",
    "vendor": "Midjourney",
    "color": "oklch(0.5 0.2 91)",
    "website_url": ""
  },
  {
    "name": "SphereLogic 6",
    "category": "Legal Tech",
    "score": 85.8,
    "price": "$20/mo",
    "vendor": "Midjourney",
    "color": "oklch(0.6 0.2 200)",
    "website_url": ""
  },
  {
    "name": "SynapseVertex 6",
    "category": "Healthcare",
    "score": 88,
    "price": "Free",
    "vendor": "Adobe",
    "color": "oklch(0.8 0.2 53)",
    "website_url": ""
  },
  {
    "name": "NextPro 8",
    "category": "Finance & Accounting",
    "score": 73.5,
    "price": "Free",
    "vendor": "Midjourney",
    "color": "oklch(0.4 0.1 332)",
    "website_url": ""
  },
  {
    "name": "VisionCore 3",
    "category": "HR & Recruiting",
    "score": 80.4,
    "price": "Enterprise",
    "vendor": "Notion",
    "color": "oklch(0.8 0.1 58)",
    "website_url": ""
  },
  {
    "name": "CyberVision 2",
    "category": "Sales & CRM",
    "score": 79.6,
    "price": "Enterprise",
    "vendor": "Autodesk",
    "color": "oklch(0.7 0.1 23)",
    "website_url": ""
  },
  {
    "name": "AlphaLumina",
    "category": "Content Marketing",
    "score": 71.1,
    "price": "$20/mo",
    "vendor": "AWS",
    "color": "oklch(0.4 0.1 233)",
    "website_url": ""
  },
  {
    "name": "MindHub 6",
    "category": "Data Analysis",
    "score": 82.3,
    "price": "Enterprise",
    "vendor": "Apple",
    "color": "oklch(0.4 0.1 129)",
    "website_url": ""
  },
  {
    "name": "EchoVertex 3",
    "category": "Customer Support",
    "score": 79.8,
    "price": "Enterprise",
    "vendor": "Mistral",
    "color": "oklch(0.7 0.1 10)",
    "website_url": ""
  },
  {
    "name": "MindGPT 2",
    "category": "Education",
    "score": 79.2,
    "price": "$20/mo",
    "vendor": "Notion",
    "color": "oklch(0.7 0.2 84)",
    "website_url": ""
  },
  {
    "name": "HyperHyper 8",
    "category": "Research",
    "score": 80.2,
    "price": "$20/mo",
    "vendor": "Perplexity",
    "color": "oklch(0.5 0.1 275)",
    "website_url": ""
  },
  {
    "name": "TechVision 7",
    "category": "Copywriting",
    "score": 81.3,
    "price": "Free",
    "vendor": "Oracle",
    "color": "oklch(0.8 0.1 193)",
    "website_url": ""
  },
  {
    "name": "NextVertex",
    "category": "SEO",
    "score": 73.3,
    "price": "Enterprise",
    "vendor": "Slack",
    "color": "oklch(0.8 0.1 39)",
    "website_url": ""
  },
  {
    "name": "CloudCloud 3",
    "category": "Social Media",
    "score": 93.9,
    "price": "Free",
    "vendor": "AI21",
    "color": "oklch(0.7 0.2 37)",
    "website_url": ""
  },
  {
    "name": "TechTech 6",
    "category": "Email Marketing",
    "score": 95.5,
    "price": "Free",
    "vendor": "Anthropic",
    "color": "oklch(0.5 0.2 51)",
    "website_url": ""
  },
  {
    "name": "NeuroNext 9",
    "category": "Business Strategy",
    "score": 98.4,
    "price": "$20/mo",
    "vendor": "Mistral",
    "color": "oklch(0.7 0.2 179)",
    "website_url": ""
  },
  {
    "name": "WavePro 5",
    "category": "Project Management",
    "score": 73.4,
    "price": "Free",
    "vendor": "ByteDance",
    "color": "oklch(0.6 0.2 248)",
    "website_url": ""
  },
  {
    "name": "LogicGrid",
    "category": "Brainstorming",
    "score": 93.9,
    "price": "$20/mo",
    "vendor": "Canva",
    "color": "oklch(0.5 0.1 173)",
    "website_url": ""
  },
  {
    "name": "QuantumCloud 8",
    "category": "Personal Growth",
    "score": 87.7,
    "price": "Free",
    "vendor": "Perplexity",
    "color": "oklch(0.7 0.2 302)",
    "website_url": ""
  },
  {
    "name": "QuantumHub 5",
    "category": "Gaming",
    "score": 94.9,
    "price": "$20/mo",
    "vendor": "Nvidia",
    "color": "oklch(0.7 0.1 92)",
    "website_url": ""
  },
  {
    "name": "CorePulse",
    "category": "Cybersecurity",
    "score": 70.7,
    "price": "Enterprise",
    "vendor": "Slack",
    "color": "oklch(0.7 0.2 271)",
    "website_url": ""
  },
  {
    "name": "VertexMeta",
    "category": "DevOps",
    "score": 83.9,
    "price": "$20/mo",
    "vendor": "Apple",
    "color": "oklch(0.6 0.1 229)",
    "website_url": ""
  },
  {
    "name": "GridGPT 2",
    "category": "Testing",
    "score": 96.1,
    "price": "$20/mo",
    "vendor": "HuggingFace",
    "color": "oklch(0.8 0.1 44)",
    "website_url": ""
  },
  {
    "name": "MatrixTech 2",
    "category": "Translation",
    "score": 90,
    "price": "$20/mo",
    "vendor": "Google",
    "color": "oklch(0.6 0.2 210)",
    "website_url": ""
  },
  {
    "name": "GenHyper",
    "category": "3D Generation",
    "score": 91,
    "price": "Free",
    "vendor": "Cohere",
    "color": "oklch(0.6 0.1 102)",
    "website_url": ""
  },
  {
    "name": "WiseNova 1",
    "category": "Robotics",
    "score": 81.1,
    "price": "Enterprise",
    "vendor": "Baidu",
    "color": "oklch(0.5 0.1 19)",
    "website_url": ""
  },
  {
    "name": "GenGPT 2",
    "category": "Agriculture",
    "score": 83.5,
    "price": "Free",
    "vendor": "Nvidia",
    "color": "oklch(0.7 0.1 39)",
    "website_url": ""
  },
  {
    "name": "AlphaNode 8",
    "category": "Real Estate",
    "score": 87.3,
    "price": "Free",
    "vendor": "Notion",
    "color": "oklch(0.6 0.1 186)",
    "website_url": ""
  },
  {
    "name": "FlowGrid",
    "category": "Logistics",
    "score": 75.3,
    "price": "Free",
    "vendor": "Google",
    "color": "oklch(0.6 0.1 206)",
    "website_url": ""
  },
  {
    "name": "CyberNext 9",
    "category": "Manufacturing",
    "score": 94,
    "price": "$20/mo",
    "vendor": "Adobe",
    "color": "oklch(0.6 0.1 173)",
    "website_url": ""
  },
  {
    "name": "SynapseSphere 8",
    "category": "Chatbots & Companions",
    "score": 80.7,
    "price": "Free",
    "vendor": "AI21",
    "color": "oklch(0.4 0.1 315)",
    "website_url": ""
  },
  {
    "name": "SynapseMind 1",
    "category": "Coding & Development",
    "score": 87.2,
    "price": "Enterprise",
    "vendor": "Perplexity",
    "color": "oklch(0.8 0.2 298)",
    "website_url": ""
  },
  {
    "name": "NexusTech 9",
    "category": "Enterprise Search",
    "score": 96.6,
    "price": "Enterprise",
    "vendor": "AWS",
    "color": "oklch(0.8 0.1 179)",
    "website_url": ""
  },
  {
    "name": "BrainWave 2",
    "category": "Productivity & Workflows",
    "score": 88.6,
    "price": "Free",
    "vendor": "Oracle",
    "color": "oklch(0.5 0.2 284)",
    "website_url": ""
  },
  {
    "name": "VertexHub 3",
    "category": "Video Generation",
    "score": 71.1,
    "price": "$20/mo",
    "vendor": "Google",
    "color": "oklch(0.8 0.1 257)",
    "website_url": ""
  },
  {
    "name": "AuraBase 4",
    "category": "Image Generation",
    "score": 90.8,
    "price": "Free",
    "vendor": "Nvidia",
    "color": "oklch(0.4 0.2 2)",
    "website_url": ""
  },
  {
    "name": "QuantumOmni 1",
    "category": "Music & Audio",
    "score": 98,
    "price": "$20/mo",
    "vendor": "Google",
    "color": "oklch(0.8 0.2 211)",
    "website_url": ""
  },
  {
    "name": "WavePulse 2",
    "category": "Meeting Assistants",
    "score": 81,
    "price": "Enterprise",
    "vendor": "IBM",
    "color": "oklch(0.4 0.1 210)",
    "website_url": ""
  },
  {
    "name": "NeuroMind 5",
    "category": "Graphic Design",
    "score": 92.2,
    "price": "Enterprise",
    "vendor": "AI21",
    "color": "oklch(0.7 0.1 283)",
    "website_url": ""
  },
  {
    "name": "LuminaWave 7",
    "category": "Voice Generation",
    "score": 77.6,
    "price": "Free",
    "vendor": "Salesforce",
    "color": "oklch(0.4 0.1 135)",
    "website_url": ""
  },
  {
    "name": "HyperVision 8",
    "category": "App & Website Builders",
    "score": 95.4,
    "price": "Enterprise",
    "vendor": "Autodesk",
    "color": "oklch(0.5 0.2 45)",
    "website_url": ""
  },
  {
    "name": "AuraMeta 7",
    "category": "Legal Tech",
    "score": 70.8,
    "price": "Free",
    "vendor": "AWS",
    "color": "oklch(0.6 0.2 201)",
    "website_url": ""
  },
  {
    "name": "MetaAlpha 2",
    "category": "Healthcare",
    "score": 70.7,
    "price": "Enterprise",
    "vendor": "Autodesk",
    "color": "oklch(0.4 0.1 10)",
    "website_url": ""
  },
  {
    "name": "TechOmni 7",
    "category": "Finance & Accounting",
    "score": 87,
    "price": "$20/mo",
    "vendor": "Oracle",
    "color": "oklch(0.4 0.2 305)",
    "website_url": ""
  },
  {
    "name": "WavePulse",
    "category": "HR & Recruiting",
    "score": 80.7,
    "price": "Free",
    "vendor": "HuggingFace",
    "color": "oklch(0.8 0.1 24)",
    "website_url": ""
  },
  {
    "name": "MetaSync 9",
    "category": "Sales & CRM",
    "score": 85.2,
    "price": "$20/mo",
    "vendor": "Inflection",
    "color": "oklch(0.4 0.1 282)",
    "website_url": ""
  },
  {
    "name": "WaveSmart 3",
    "category": "Content Marketing",
    "score": 99.2,
    "price": "Enterprise",
    "vendor": "Apple",
    "color": "oklch(0.4 0.2 207)",
    "website_url": ""
  },
  {
    "name": "FlowCloud",
    "category": "Data Analysis",
    "score": 83.3,
    "price": "Free",
    "vendor": "HuggingFace",
    "color": "oklch(0.7 0.2 252)",
    "website_url": ""
  },
  {
    "name": "LogicDeep 7",
    "category": "Customer Support",
    "score": 93.4,
    "price": "Enterprise",
    "vendor": "Microsoft",
    "color": "oklch(0.5 0.1 288)",
    "website_url": ""
  },
  {
    "name": "WaveData 9",
    "category": "Education",
    "score": 96.4,
    "price": "$20/mo",
    "vendor": "Midjourney",
    "color": "oklch(0.8 0.1 134)",
    "website_url": ""
  },
  {
    "name": "PulseOmni 6",
    "category": "Research",
    "score": 95.4,
    "price": "Enterprise",
    "vendor": "SAP",
    "color": "oklch(0.8 0.2 130)",
    "website_url": ""
  },
  {
    "name": "GridSync 7",
    "category": "Copywriting",
    "score": 90.9,
    "price": "Free",
    "vendor": "Stability AI",
    "color": "oklch(0.8 0.2 197)",
    "website_url": ""
  },
  {
    "name": "SynapseVision 7",
    "category": "SEO",
    "score": 82.6,
    "price": "$20/mo",
    "vendor": "Autodesk",
    "color": "oklch(0.5 0.2 225)",
    "website_url": ""
  },
  {
    "name": "VertexCloud 8",
    "category": "Social Media",
    "score": 92.8,
    "price": "Enterprise",
    "vendor": "ByteDance",
    "color": "oklch(0.4 0.2 168)",
    "website_url": ""
  },
  {
    "name": "AlphaHyper 6",
    "category": "Email Marketing",
    "score": 78.8,
    "price": "Free",
    "vendor": "Stability AI",
    "color": "oklch(0.5 0.2 61)",
    "website_url": ""
  },
  {
    "name": "DeepNova 6",
    "category": "Business Strategy",
    "score": 96.5,
    "price": "Enterprise",
    "vendor": "Slack",
    "color": "oklch(0.6 0.1 303)",
    "website_url": ""
  },
  {
    "name": "AlphaGrid 1",
    "category": "Project Management",
    "score": 72.8,
    "price": "Free",
    "vendor": "Nvidia",
    "color": "oklch(0.7 0.2 342)",
    "website_url": ""
  },
  {
    "name": "MatrixNext 8",
    "category": "Brainstorming",
    "score": 98.9,
    "price": "$20/mo",
    "vendor": "Mistral",
    "color": "oklch(0.8 0.2 177)",
    "website_url": ""
  },
  {
    "name": "LuminaEcho 6",
    "category": "Personal Growth",
    "score": 94.5,
    "price": "Enterprise",
    "vendor": "Adobe",
    "color": "oklch(0.6 0.1 344)",
    "website_url": ""
  },
  {
    "name": "NeuroNext 6",
    "category": "Gaming",
    "score": 78.5,
    "price": "Free",
    "vendor": "Alibaba",
    "color": "oklch(0.8 0.2 329)",
    "website_url": ""
  },
  {
    "name": "AuraBrain 7",
    "category": "Cybersecurity",
    "score": 71.5,
    "price": "$20/mo",
    "vendor": "ByteDance",
    "color": "oklch(0.4 0.2 216)",
    "website_url": ""
  },
  {
    "name": "OmniDeep",
    "category": "DevOps",
    "score": 83.9,
    "price": "Enterprise",
    "vendor": "Cohere",
    "color": "oklch(0.7 0.1 284)",
    "website_url": ""
  },
  {
    "name": "WaveNexus 2",
    "category": "Testing",
    "score": 81.5,
    "price": "Enterprise",
    "vendor": "OpenAI",
    "color": "oklch(0.8 0.1 159)",
    "website_url": ""
  },
  {
    "name": "DeepVision 5",
    "category": "Translation",
    "score": 89.5,
    "price": "$20/mo",
    "vendor": "IBM",
    "color": "oklch(0.4 0.2 341)",
    "website_url": ""
  },
  {
    "name": "EchoWave 1",
    "category": "3D Generation",
    "score": 85.3,
    "price": "$20/mo",
    "vendor": "Slack",
    "color": "oklch(0.6 0.2 59)",
    "website_url": ""
  },
  {
    "name": "PulseNode 7",
    "category": "Robotics",
    "score": 93.6,
    "price": "$20/mo",
    "vendor": "SAP",
    "color": "oklch(0.6 0.1 125)",
    "website_url": ""
  },
  {
    "name": "DeepSpark 8",
    "category": "Agriculture",
    "score": 84.2,
    "price": "Free",
    "vendor": "Google",
    "color": "oklch(0.8 0.1 160)",
    "website_url": ""
  },
  {
    "name": "BrainNode 5",
    "category": "Real Estate",
    "score": 75.1,
    "price": "$20/mo",
    "vendor": "xAI",
    "color": "oklch(0.5 0.2 295)",
    "website_url": ""
  },
  {
    "name": "DeepLogic 5",
    "category": "Logistics",
    "score": 88.2,
    "price": "$20/mo",
    "vendor": "Autodesk",
    "color": "oklch(0.8 0.1 181)",
    "website_url": ""
  },
  {
    "name": "HyperNova 8",
    "category": "Manufacturing",
    "score": 75.8,
    "price": "Enterprise",
    "vendor": "HuggingFace",
    "color": "oklch(0.7 0.2 200)",
    "website_url": ""
  },
  {
    "name": "OmniGen 9",
    "category": "Chatbots & Companions",
    "score": 74.5,
    "price": "Enterprise",
    "vendor": "Alibaba",
    "color": "oklch(0.5 0.1 274)",
    "website_url": ""
  },
  {
    "name": "SynapseVertex 8",
    "category": "Coding & Development",
    "score": 73.1,
    "price": "$20/mo",
    "vendor": "Google",
    "color": "oklch(0.6 0.2 152)",
    "website_url": ""
  },
  {
    "name": "DataBase 4",
    "category": "Enterprise Search",
    "score": 88.2,
    "price": "Free",
    "vendor": "Notion",
    "color": "oklch(0.7 0.1 298)",
    "website_url": ""
  },
  {
    "name": "HyperMeta 3",
    "category": "Productivity & Workflows",
    "score": 70.7,
    "price": "Free",
    "vendor": "Apple",
    "color": "oklch(0.5 0.2 139)",
    "website_url": ""
  },
  {
    "name": "FlowEcho",
    "category": "Video Generation",
    "score": 88.7,
    "price": "Enterprise",
    "vendor": "OpenAI",
    "color": "oklch(0.4 0.1 39)",
    "website_url": ""
  },
  {
    "name": "ProPro 2",
    "category": "Image Generation",
    "score": 82.3,
    "price": "Free",
    "vendor": "Oracle",
    "color": "oklch(0.7 0.2 3)",
    "website_url": ""
  },
  {
    "name": "BrainNext 7",
    "category": "Music & Audio",
    "score": 72,
    "price": "Enterprise",
    "vendor": "Canva",
    "color": "oklch(0.5 0.2 113)",
    "website_url": ""
  },
  {
    "name": "AuraHub 6",
    "category": "Meeting Assistants",
    "score": 74.3,
    "price": "Free",
    "vendor": "Apple",
    "color": "oklch(0.7 0.2 304)",
    "website_url": ""
  },
  {
    "name": "AutoGPT 5",
    "category": "Graphic Design",
    "score": 87.8,
    "price": "$20/mo",
    "vendor": "IBM",
    "color": "oklch(0.8 0.2 199)",
    "website_url": ""
  },
  {
    "name": "BotSynthetix 8",
    "category": "Voice Generation",
    "score": 76,
    "price": "Free",
    "vendor": "Canva",
    "color": "oklch(0.5 0.2 249)",
    "website_url": ""
  },
  {
    "name": "VisionVision 4",
    "category": "Legal Tech",
    "score": 81.9,
    "price": "Free",
    "vendor": "HuggingFace",
    "color": "oklch(0.8 0.1 179)",
    "website_url": ""
  },
  {
    "name": "ProOmni 5",
    "category": "Healthcare",
    "score": 83.1,
    "price": "Free",
    "vendor": "Oracle",
    "color": "oklch(0.7 0.2 328)",
    "website_url": ""
  },
  {
    "name": "MindWise 1",
    "category": "Finance & Accounting",
    "score": 82,
    "price": "Enterprise",
    "vendor": "OpenAI",
    "color": "oklch(0.7 0.2 163)",
    "website_url": ""
  },
  {
    "name": "BrainSynthetix 5",
    "category": "HR & Recruiting",
    "score": 90.5,
    "price": "Free",
    "vendor": "Nvidia",
    "color": "oklch(0.4 0.1 48)",
    "website_url": ""
  },
  {
    "name": "LinkDeep 5",
    "category": "Sales & CRM",
    "score": 83.2,
    "price": "$20/mo",
    "vendor": "AWS",
    "color": "oklch(0.8 0.1 118)",
    "website_url": ""
  },
  {
    "name": "LuminaSphere 5",
    "category": "Content Marketing",
    "score": 95.5,
    "price": "Enterprise",
    "vendor": "SAP",
    "color": "oklch(0.7 0.1 206)",
    "website_url": ""
  },
  {
    "name": "CloudTech 7",
    "category": "Data Analysis",
    "score": 73.8,
    "price": "Enterprise",
    "vendor": "Cohere",
    "color": "oklch(0.6 0.2 258)",
    "website_url": ""
  },
  {
    "name": "VertexGen 2",
    "category": "Customer Support",
    "score": 87.7,
    "price": "$20/mo",
    "vendor": "Perplexity",
    "color": "oklch(0.6 0.2 101)",
    "website_url": ""
  },
  {
    "name": "MindMatrix 9",
    "category": "Education",
    "score": 89.5,
    "price": "Enterprise",
    "vendor": "Anthropic",
    "color": "oklch(0.6 0.2 39)",
    "website_url": ""
  },
  {
    "name": "NexusWave 4",
    "category": "Research",
    "score": 98.4,
    "price": "$20/mo",
    "vendor": "Inflection",
    "color": "oklch(0.8 0.1 286)",
    "website_url": ""
  },
  {
    "name": "PulseNext 7",
    "category": "Copywriting",
    "score": 96.6,
    "price": "Free",
    "vendor": "ByteDance",
    "color": "oklch(0.8 0.2 180)",
    "website_url": ""
  },
  {
    "name": "DeepBase 3",
    "category": "SEO",
    "score": 90.2,
    "price": "Free",
    "vendor": "OpenAI",
    "color": "oklch(0.6 0.1 307)",
    "website_url": ""
  },
  {
    "name": "LuminaWise 9",
    "category": "Social Media",
    "score": 89.4,
    "price": "Enterprise",
    "vendor": "Stability AI",
    "color": "oklch(0.5 0.2 174)",
    "website_url": ""
  },
  {
    "name": "VisionAI 4",
    "category": "Email Marketing",
    "score": 91.1,
    "price": "Free",
    "vendor": "Slack",
    "color": "oklch(0.6 0.1 318)",
    "website_url": ""
  },
  {
    "name": "EchoDeep 7",
    "category": "Business Strategy",
    "score": 93.8,
    "price": "Free",
    "vendor": "Autodesk",
    "color": "oklch(0.5 0.2 78)",
    "website_url": ""
  },
  {
    "name": "SyncHub 5",
    "category": "Project Management",
    "score": 90.8,
    "price": "Enterprise",
    "vendor": "AI21",
    "color": "oklch(0.6 0.2 131)",
    "website_url": ""
  },
  {
    "name": "MatrixSpark 3",
    "category": "Brainstorming",
    "score": 70.5,
    "price": "Free",
    "vendor": "Salesforce",
    "color": "oklch(0.7 0.2 158)",
    "website_url": ""
  },
  {
    "name": "LuminaMind 2",
    "category": "Personal Growth",
    "score": 85.8,
    "price": "Free",
    "vendor": "Alibaba",
    "color": "oklch(0.5 0.1 197)",
    "website_url": ""
  },
  {
    "name": "TechCore 6",
    "category": "Gaming",
    "score": 89.4,
    "price": "Enterprise",
    "vendor": "Autodesk",
    "color": "oklch(0.8 0.1 26)",
    "website_url": ""
  },
  {
    "name": "AuraSpark 6",
    "category": "Cybersecurity",
    "score": 84.6,
    "price": "Enterprise",
    "vendor": "AI21",
    "color": "oklch(0.6 0.2 354)",
    "website_url": ""
  },
  {
    "name": "WaveSpark 3",
    "category": "DevOps",
    "score": 84.4,
    "price": "$20/mo",
    "vendor": "Microsoft",
    "color": "oklch(0.6 0.2 210)",
    "website_url": ""
  },
  {
    "name": "SparkLogic 4",
    "category": "Testing",
    "score": 90.3,
    "price": "Free",
    "vendor": "Notion",
    "color": "oklch(0.4 0.2 278)",
    "website_url": ""
  },
  {
    "name": "CyberSphere 7",
    "category": "Translation",
    "score": 80.8,
    "price": "Free",
    "vendor": "Baidu",
    "color": "oklch(0.4 0.1 159)",
    "website_url": ""
  },
  {
    "name": "DataVision 1",
    "category": "3D Generation",
    "score": 83.3,
    "price": "Free",
    "vendor": "xAI",
    "color": "oklch(0.4 0.1 348)",
    "website_url": ""
  },
  {
    "name": "QuantumNova 5",
    "category": "Robotics",
    "score": 70.9,
    "price": "$20/mo",
    "vendor": "AWS",
    "color": "oklch(0.5 0.2 5)",
    "website_url": ""
  },
  {
    "name": "LuminaMatrix 3",
    "category": "Agriculture",
    "score": 78.1,
    "price": "Free",
    "vendor": "Oracle",
    "color": "oklch(0.4 0.2 190)",
    "website_url": ""
  },
  {
    "name": "TechSphere",
    "category": "Real Estate",
    "score": 75.1,
    "price": "Free",
    "vendor": "OpenAI",
    "color": "oklch(0.6 0.2 95)",
    "website_url": ""
  },
  {
    "name": "AuraOmni 4",
    "category": "Logistics",
    "score": 85.3,
    "price": "$20/mo",
    "vendor": "Meta",
    "color": "oklch(0.4 0.2 179)",
    "website_url": ""
  },
  {
    "name": "LuminaVertex 4",
    "category": "Manufacturing",
    "score": 85.8,
    "price": "$20/mo",
    "vendor": "AI21",
    "color": "oklch(0.4 0.2 161)",
    "website_url": ""
  },
  {
    "name": "VertexNexus 1",
    "category": "Chatbots & Companions",
    "score": 77.2,
    "price": "$20/mo",
    "vendor": "Cohere",
    "color": "oklch(0.8 0.1 72)",
    "website_url": ""
  },
  {
    "name": "PulseNode 2",
    "category": "Coding & Development",
    "score": 81.6,
    "price": "Free",
    "vendor": "Google",
    "color": "oklch(0.8 0.1 284)",
    "website_url": ""
  },
  {
    "name": "VertexDeep 6",
    "category": "Enterprise Search",
    "score": 76.9,
    "price": "Free",
    "vendor": "Stability AI",
    "color": "oklch(0.4 0.2 98)",
    "website_url": ""
  },
  {
    "name": "SmartNext 7",
    "category": "Productivity & Workflows",
    "score": 92.1,
    "price": "Enterprise",
    "vendor": "AWS",
    "color": "oklch(0.8 0.1 6)",
    "website_url": ""
  },
  {
    "name": "DataCore 3",
    "category": "Content Marketing",
    "score": 92.5,
    "price": "$20/mo",
    "vendor": "Notion",
    "color": "oklch(0.5 0.1 12)",
    "website_url": ""
  },
  {
    "name": "NextSync 4",
    "category": "Image Generation",
    "score": 96.5,
    "price": "Free",
    "vendor": "Notion",
    "color": "oklch(0.6 0.2 148)",
    "website_url": ""
  },
  {
    "name": "CoreMatrix",
    "category": "Music & Audio",
    "score": 76.5,
    "price": "Enterprise",
    "vendor": "Canva",
    "color": "oklch(0.5 0.1 217)",
    "website_url": ""
  },
  {
    "name": "GridBot 4",
    "category": "Meeting Assistants",
    "score": 74.9,
    "price": "$20/mo",
    "vendor": "Autodesk",
    "color": "oklch(0.4 0.1 78)",
    "website_url": ""
  },
  {
    "name": "SpherePro",
    "category": "Graphic Design",
    "score": 87.1,
    "price": "Free",
    "vendor": "Anthropic",
    "color": "oklch(0.8 0.2 259)",
    "website_url": ""
  },
  {
    "name": "CoreNova 1",
    "category": "Voice Generation",
    "score": 76.1,
    "price": "Free",
    "vendor": "AI21",
    "color": "oklch(0.4 0.1 326)",
    "website_url": ""
  },
  {
    "name": "TechBot 7",
    "category": "App & Website Builders",
    "score": 77.6,
    "price": "$20/mo",
    "vendor": "Midjourney",
    "color": "oklch(0.6 0.1 320)",
    "website_url": ""
  },
  {
    "name": "AuraAI",
    "category": "Project Management",
    "score": 86.6,
    "price": "$20/mo",
    "vendor": "Google",
    "color": "oklch(0.6 0.1 138)",
    "website_url": ""
  },
  {
    "name": "FlowCore 6",
    "category": "Healthcare",
    "score": 87.1,
    "price": "Enterprise",
    "vendor": "Cohere",
    "color": "oklch(0.8 0.2 326)",
    "website_url": ""
  },
  {
    "name": "AlphaLogic 4",
    "category": "Business Strategy",
    "score": 97.3,
    "price": "Enterprise",
    "vendor": "Tencent",
    "color": "oklch(0.6 0.2 335)",
    "website_url": ""
  },
  {
    "name": "SmartGPT 3",
    "category": "HR & Recruiting",
    "score": 86.1,
    "price": "$20/mo",
    "vendor": "Mistral",
    "color": "oklch(0.5 0.2 189)",
    "website_url": ""
  },
  {
    "name": "AutoHyper 1",
    "category": "Sales & CRM",
    "score": 77.1,
    "price": "Free",
    "vendor": "Baidu",
    "color": "oklch(0.4 0.1 136)",
    "website_url": ""
  },
  {
    "name": "SynthetixFlow 1",
    "category": "Content Marketing",
    "score": 70.2,
    "price": "Free",
    "vendor": "Tencent",
    "color": "oklch(0.5 0.1 349)",
    "website_url": ""
  },
  {
    "name": "SparkMeta 4",
    "category": "Data Analysis",
    "score": 86.5,
    "price": "$20/mo",
    "vendor": "Oracle",
    "color": "oklch(0.4 0.2 298)",
    "website_url": ""
  },
  {
    "name": "WiseCloud 3",
    "category": "Customer Support",
    "score": 88.2,
    "price": "Enterprise",
    "vendor": "Cohere",
    "color": "oklch(0.6 0.2 338)",
    "website_url": ""
  },
  {
    "name": "NovaVision 5",
    "category": "Education",
    "score": 74.7,
    "price": "Free",
    "vendor": "Meta",
    "color": "oklch(0.4 0.2 264)",
    "website_url": ""
  },
  {
    "name": "PulseHub 6",
    "category": "Research",
    "score": 91.6,
    "price": "$20/mo",
    "vendor": "Inflection",
    "color": "oklch(0.6 0.1 245)",
    "website_url": ""
  },
  {
    "name": "LinkOmni 1",
    "category": "Copywriting",
    "score": 73.4,
    "price": "Free",
    "vendor": "Nvidia",
    "color": "oklch(0.4 0.1 355)",
    "website_url": ""
  },
  {
    "name": "NextWise",
    "category": "SEO",
    "score": 95.1,
    "price": "Free",
    "vendor": "Anthropic",
    "color": "oklch(0.5 0.1 156)",
    "website_url": ""
  },
  {
    "name": "AuraSphere 4",
    "category": "Social Media",
    "score": 84.4,
    "price": "Free",
    "vendor": "Midjourney",
    "color": "oklch(0.8 0.1 10)",
    "website_url": ""
  },
  {
    "name": "NexusCloud 3",
    "category": "Email Marketing",
    "score": 87,
    "price": "Enterprise",
    "vendor": "Baidu",
    "color": "oklch(0.5 0.2 272)",
    "website_url": ""
  },
  {
    "name": "SyncPro 2",
    "category": "Business Strategy",
    "score": 71.6,
    "price": "Free",
    "vendor": "Google",
    "color": "oklch(0.8 0.1 86)",
    "website_url": ""
  },
  {
    "name": "NovaBase 5",
    "category": "Project Management",
    "score": 86.3,
    "price": "Free",
    "vendor": "xAI",
    "color": "oklch(0.6 0.2 82)",
    "website_url": ""
  },
  {
    "name": "FlowMind 1",
    "category": "Brainstorming",
    "score": 93.3,
    "price": "Enterprise",
    "vendor": "Inflection",
    "color": "oklch(0.7 0.1 283)",
    "website_url": ""
  },
  {
    "name": "VertexPro 2",
    "category": "Personal Growth",
    "score": 84.9,
    "price": "$20/mo",
    "vendor": "AI21",
    "color": "oklch(0.7 0.2 199)",
    "website_url": ""
  },
  {
    "name": "OmniLink 2",
    "category": "Gaming",
    "score": 77.3,
    "price": "$20/mo",
    "vendor": "Cohere",
    "color": "oklch(0.8 0.2 108)",
    "website_url": ""
  },
  {
    "name": "BrainPulse",
    "category": "Cybersecurity",
    "score": 80.6,
    "price": "Free",
    "vendor": "IBM",
    "color": "oklch(0.5 0.1 164)",
    "website_url": ""
  },
  {
    "name": "CyberVertex 4",
    "category": "DevOps",
    "score": 76.8,
    "price": "Enterprise",
    "vendor": "IBM",
    "color": "oklch(0.6 0.2 284)",
    "website_url": ""
  },
  {
    "name": "CyberData 8",
    "category": "Testing",
    "score": 92,
    "price": "Free",
    "vendor": "Meta",
    "color": "oklch(0.5 0.1 311)",
    "website_url": ""
  },
  {
    "name": "AuraLogic 5",
    "category": "Translation",
    "score": 96.4,
    "price": "$20/mo",
    "vendor": "Perplexity",
    "color": "oklch(0.4 0.1 93)",
    "website_url": ""
  },
  {
    "name": "LogicVertex 9",
    "category": "3D Generation",
    "score": 97.5,
    "price": "$20/mo",
    "vendor": "Apple",
    "color": "oklch(0.7 0.1 115)",
    "website_url": ""
  },
  {
    "name": "GenSmart 8",
    "category": "Robotics",
    "score": 93.2,
    "price": "$20/mo",
    "vendor": "Adobe",
    "color": "oklch(0.4 0.2 193)",
    "website_url": ""
  },
  {
    "name": "NeuroNext 2",
    "category": "Agriculture",
    "score": 97.3,
    "price": "$20/mo",
    "vendor": "AWS",
    "color": "oklch(0.7 0.2 263)",
    "website_url": ""
  },
  {
    "name": "MindAI 7",
    "category": "Real Estate",
    "score": 70,
    "price": "Enterprise",
    "vendor": "Perplexity",
    "color": "oklch(0.4 0.2 3)",
    "website_url": ""
  },
  {
    "name": "BotWise 6",
    "category": "Logistics",
    "score": 75,
    "price": "$20/mo",
    "vendor": "xAI",
    "color": "oklch(0.4 0.2 307)",
    "website_url": ""
  },
  {
    "name": "SyncGPT 5",
    "category": "Manufacturing",
    "score": 73.6,
    "price": "Free",
    "vendor": "Apple",
    "color": "oklch(0.8 0.1 96)",
    "website_url": ""
  },
  {
    "name": "SphereDeep",
    "category": "Chatbots & Companions",
    "score": 86.8,
    "price": "Enterprise",
    "vendor": "Stability AI",
    "color": "oklch(0.8 0.1 217)",
    "website_url": ""
  },
  {
    "name": "PulseAlpha 2",
    "category": "Coding & Development",
    "score": 95.8,
    "price": "Enterprise",
    "vendor": "ByteDance",
    "color": "oklch(0.5 0.1 1)",
    "website_url": ""
  },
  {
    "name": "SynapseData 9",
    "category": "Enterprise Search",
    "score": 88.9,
    "price": "Enterprise",
    "vendor": "Alibaba",
    "color": "oklch(0.6 0.2 82)",
    "website_url": ""
  },
  {
    "name": "MetaGen 3",
    "category": "Productivity & Workflows",
    "score": 77.6,
    "price": "$20/mo",
    "vendor": "xAI",
    "color": "oklch(0.6 0.1 157)",
    "website_url": ""
  },
  {
    "name": "LinkLogic 3",
    "category": "Video Generation",
    "score": 91.7,
    "price": "$20/mo",
    "vendor": "Cohere",
    "color": "oklch(0.4 0.2 265)",
    "website_url": ""
  },
  {
    "name": "NexusMeta 8",
    "category": "Image Generation",
    "score": 88.4,
    "price": "$20/mo",
    "vendor": "Nvidia",
    "color": "oklch(0.6 0.1 92)",
    "website_url": ""
  },
  {
    "name": "CoreWave 2",
    "category": "Music & Audio",
    "score": 70.3,
    "price": "$20/mo",
    "vendor": "Mistral",
    "color": "oklch(0.6 0.1 47)",
    "website_url": ""
  },
  {
    "name": "HyperGrid 2",
    "category": "Meeting Assistants",
    "score": 97.4,
    "price": "Enterprise",
    "vendor": "Microsoft",
    "color": "oklch(0.7 0.2 12)",
    "website_url": ""
  },
  {
    "name": "GenLogic 4",
    "category": "Graphic Design",
    "score": 73.9,
    "price": "Enterprise",
    "vendor": "Microsoft",
    "color": "oklch(0.5 0.1 144)",
    "website_url": ""
  },
  {
    "name": "MetaGen 6",
    "category": "Voice Generation",
    "score": 74.2,
    "price": "Free",
    "vendor": "Perplexity",
    "color": "oklch(0.6 0.2 320)",
    "website_url": ""
  },
  {
    "name": "EchoGrid 8",
    "category": "App & Website Builders",
    "score": 86.5,
    "price": "Free",
    "vendor": "HuggingFace",
    "color": "oklch(0.6 0.1 189)",
    "website_url": ""
  },
  {
    "name": "SmartNode 3",
    "category": "Legal Tech",
    "score": 86.4,
    "price": "Enterprise",
    "vendor": "Meta",
    "color": "oklch(0.7 0.1 345)",
    "website_url": ""
  },
  {
    "name": "MetaPro",
    "category": "Healthcare",
    "score": 78.3,
    "price": "$20/mo",
    "vendor": "Cohere",
    "color": "oklch(0.5 0.2 132)",
    "website_url": ""
  },
  {
    "name": "LinkAI 2",
    "category": "Finance & Accounting",
    "score": 84.1,
    "price": "$20/mo",
    "vendor": "Autodesk",
    "color": "oklch(0.5 0.2 37)",
    "website_url": ""
  },
  {
    "name": "BrainSmart 2",
    "category": "HR & Recruiting",
    "score": 93.2,
    "price": "Enterprise",
    "vendor": "Adobe",
    "color": "oklch(0.7 0.2 279)",
    "website_url": ""
  },
  {
    "name": "GenOmni 2",
    "category": "Sales & CRM",
    "score": 80.5,
    "price": "Enterprise",
    "vendor": "Canva",
    "color": "oklch(0.4 0.1 167)",
    "website_url": ""
  },
  {
    "name": "QuantumWise 2",
    "category": "Data Analysis",
    "score": 72,
    "price": "Enterprise",
    "vendor": "Adobe",
    "color": "oklch(0.7 0.2 306)",
    "website_url": ""
  },
  {
    "name": "OmniSpark 2",
    "category": "Customer Support",
    "score": 86,
    "price": "Enterprise",
    "vendor": "AI21",
    "color": "oklch(0.5 0.2 248)",
    "website_url": ""
  },
  {
    "name": "TechDeep 3",
    "category": "Education",
    "score": 90.4,
    "price": "Enterprise",
    "vendor": "xAI",
    "color": "oklch(0.4 0.1 17)",
    "website_url": ""
  },
  {
    "name": "ProGen 6",
    "category": "Research",
    "score": 93,
    "price": "Free",
    "vendor": "Autodesk",
    "color": "oklch(0.7 0.1 338)",
    "website_url": ""
  },
  {
    "name": "WiseHyper 2",
    "category": "Copywriting",
    "score": 78.1,
    "price": "Free",
    "vendor": "Cohere",
    "color": "oklch(0.8 0.2 124)",
    "website_url": ""
  },
  {
    "name": "PulseVision 2",
    "category": "SEO",
    "score": 82.5,
    "price": "Free",
    "vendor": "Salesforce",
    "color": "oklch(0.4 0.1 118)",
    "website_url": ""
  },
  {
    "name": "CoreNova 8",
    "category": "Social Media",
    "score": 90.8,
    "price": "Free",
    "vendor": "HuggingFace",
    "color": "oklch(0.8 0.2 334)",
    "website_url": ""
  },
  {
    "name": "VisionSmart 3",
    "category": "Email Marketing",
    "score": 73.8,
    "price": "$20/mo",
    "vendor": "Stability AI",
    "color": "oklch(0.8 0.2 206)",
    "website_url": ""
  },
  {
    "name": "EchoNexus 2",
    "category": "Business Strategy",
    "score": 97.1,
    "price": "Free",
    "vendor": "Oracle",
    "color": "oklch(0.4 0.1 102)",
    "website_url": ""
  },
  {
    "name": "BotNext 1",
    "category": "Project Management",
    "score": 92.4,
    "price": "Enterprise",
    "vendor": "Perplexity",
    "color": "oklch(0.8 0.2 134)",
    "website_url": ""
  },
  {
    "name": "NextPro 2",
    "category": "Personal Growth",
    "score": 89.1,
    "price": "Enterprise",
    "vendor": "HuggingFace",
    "color": "oklch(0.5 0.2 112)",
    "website_url": ""
  },
  {
    "name": "MindNode 8",
    "category": "Gaming",
    "score": 70.4,
    "price": "Enterprise",
    "vendor": "Stability AI",
    "color": "oklch(0.7 0.1 59)",
    "website_url": ""
  },
  {
    "name": "AutoOmni 9",
    "category": "Cybersecurity",
    "score": 77.9,
    "price": "Free",
    "vendor": "ByteDance",
    "color": "oklch(0.8 0.1 320)",
    "website_url": ""
  },
  {
    "name": "LogicGPT 7",
    "category": "DevOps",
    "score": 78.1,
    "price": "Free",
    "vendor": "Midjourney",
    "color": "oklch(0.8 0.1 162)",
    "website_url": ""
  },
  {
    "name": "LinkLogic 7",
    "category": "Testing",
    "score": 79.1,
    "price": "$20/mo",
    "vendor": "IBM",
    "color": "oklch(0.4 0.1 171)",
    "website_url": ""
  },
  {
    "name": "SparkAI 8",
    "category": "Translation",
    "score": 93.1,
    "price": "$20/mo",
    "vendor": "Baidu",
    "color": "oklch(0.8 0.2 68)",
    "website_url": ""
  },
  {
    "name": "NexusVertex 4",
    "category": "3D Generation",
    "score": 79.7,
    "price": "$20/mo",
    "vendor": "Nvidia",
    "color": "oklch(0.5 0.2 297)",
    "website_url": ""
  },
  {
    "name": "WiseGrid 8",
    "category": "Robotics",
    "score": 97.5,
    "price": "$20/mo",
    "vendor": "HuggingFace",
    "color": "oklch(0.7 0.2 216)",
    "website_url": ""
  },
  {
    "name": "SynthetixSphere 4",
    "category": "Agriculture",
    "score": 74.6,
    "price": "Enterprise",
    "vendor": "Canva",
    "color": "oklch(0.6 0.1 290)",
    "website_url": ""
  },
  {
    "name": "WavePro 8",
    "category": "Real Estate",
    "score": 88.7,
    "price": "Enterprise",
    "vendor": "ByteDance",
    "color": "oklch(0.5 0.1 53)",
    "website_url": ""
  },
  {
    "name": "CoreTech 6",
    "category": "Logistics",
    "score": 79.8,
    "price": "$20/mo",
    "vendor": "xAI",
    "color": "oklch(0.8 0.2 157)",
    "website_url": ""
  },
  {
    "name": "SynthetixHub 9",
    "category": "Manufacturing",
    "score": 91.8,
    "price": "$20/mo",
    "vendor": "Inflection",
    "color": "oklch(0.6 0.2 29)",
    "website_url": ""
  },
  {
    "name": "DataGen 8",
    "category": "Chatbots & Companions",
    "score": 84.9,
    "price": "Free",
    "vendor": "Apple",
    "color": "oklch(0.8 0.1 118)",
    "website_url": ""
  },
  {
    "name": "LogicHub 8",
    "category": "Coding & Development",
    "score": 93.3,
    "price": "Free",
    "vendor": "Baidu",
    "color": "oklch(0.6 0.1 252)",
    "website_url": ""
  },
  {
    "name": "OmniPulse 5",
    "category": "Enterprise Search",
    "score": 97.3,
    "price": "Free",
    "vendor": "Mistral",
    "color": "oklch(0.4 0.1 128)",
    "website_url": ""
  },
  {
    "name": "NeuroNexus 2",
    "category": "Productivity & Workflows",
    "score": 74.2,
    "price": "Free",
    "vendor": "Nvidia",
    "color": "oklch(0.6 0.1 120)",
    "website_url": ""
  },
  {
    "name": "ProWave",
    "category": "Video Generation",
    "score": 82.6,
    "price": "Free",
    "vendor": "AI21",
    "color": "oklch(0.4 0.1 198)",
    "website_url": ""
  },
  {
    "name": "OmniVision 8",
    "category": "Image Generation",
    "score": 73.5,
    "price": "Enterprise",
    "vendor": "Slack",
    "color": "oklch(0.6 0.1 71)",
    "website_url": ""
  },
  {
    "name": "BotNode",
    "category": "Music & Audio",
    "score": 98.2,
    "price": "Enterprise",
    "vendor": "Midjourney",
    "color": "oklch(0.5 0.2 132)",
    "website_url": ""
  },
  {
    "name": "VertexFlow 6",
    "category": "Meeting Assistants",
    "score": 92.1,
    "price": "Free",
    "vendor": "Nvidia",
    "color": "oklch(0.5 0.2 100)",
    "website_url": ""
  },
  {
    "name": "BotGen 5",
    "category": "Voice Generation",
    "score": 82.7,
    "price": "$20/mo",
    "vendor": "xAI",
    "color": "oklch(0.4 0.2 287)",
    "website_url": ""
  },
  {
    "name": "AlphaPro 7",
    "category": "App & Website Builders",
    "score": 87.2,
    "price": "Enterprise",
    "vendor": "HuggingFace",
    "color": "oklch(0.4 0.2 345)",
    "website_url": ""
  },
  {
    "name": "LuminaMind 1",
    "category": "Legal Tech",
    "score": 90.4,
    "price": "$20/mo",
    "vendor": "Slack",
    "color": "oklch(0.7 0.1 35)",
    "website_url": ""
  },
  {
    "name": "WiseSync 3",
    "category": "Healthcare",
    "score": 99,
    "price": "Enterprise",
    "vendor": "OpenAI",
    "color": "oklch(0.5 0.2 240)",
    "website_url": ""
  },
  {
    "name": "NeuroBase 2",
    "category": "Finance & Accounting",
    "score": 74.8,
    "price": "$20/mo",
    "vendor": "Salesforce",
    "color": "oklch(0.8 0.1 117)",
    "website_url": ""
  },
  {
    "name": "LogicBase 6",
    "category": "HR & Recruiting",
    "score": 82,
    "price": "$20/mo",
    "vendor": "Autodesk",
    "color": "oklch(0.6 0.2 336)",
    "website_url": ""
  },
  {
    "name": "NeuroSmart 6",
    "category": "Sales & CRM",
    "score": 87.1,
    "price": "$20/mo",
    "vendor": "Perplexity",
    "color": "oklch(0.6 0.2 312)",
    "website_url": ""
  },
  {
    "name": "MetaWave 3",
    "category": "Content Marketing",
    "score": 80.5,
    "price": "Enterprise",
    "vendor": "Mistral",
    "color": "oklch(0.4 0.2 266)",
    "website_url": ""
  },
  {
    "name": "NeuroCloud 2",
    "category": "Data Analysis",
    "score": 90.1,
    "price": "Free",
    "vendor": "AI21",
    "color": "oklch(0.5 0.1 153)",
    "website_url": ""
  },
  {
    "name": "DeepAlpha 9",
    "category": "Customer Support",
    "score": 70,
    "price": "Free",
    "vendor": "Canva",
    "color": "oklch(0.8 0.1 237)",
    "website_url": ""
  },
  {
    "name": "QuantumBrain 9",
    "category": "Education",
    "score": 74.1,
    "price": "$20/mo",
    "vendor": "SAP",
    "color": "oklch(0.4 0.1 28)",
    "website_url": ""
  },
  {
    "name": "QuantumNext 9",
    "category": "Research",
    "score": 87.5,
    "price": "Free",
    "vendor": "Salesforce",
    "color": "oklch(0.5 0.2 150)",
    "website_url": ""
  },
  {
    "name": "NexusBot 8",
    "category": "Copywriting",
    "score": 81.3,
    "price": "Enterprise",
    "vendor": "AWS",
    "color": "oklch(0.8 0.1 261)",
    "website_url": ""
  },
  {
    "name": "MetaGen 1",
    "category": "SEO",
    "score": 78.5,
    "price": "Enterprise",
    "vendor": "xAI",
    "color": "oklch(0.5 0.1 287)",
    "website_url": ""
  },
  {
    "name": "OmniGen 1",
    "category": "Social Media",
    "score": 75.1,
    "price": "$20/mo",
    "vendor": "AI21",
    "color": "oklch(0.4 0.1 271)",
    "website_url": ""
  },
  {
    "name": "MetaBrain 6",
    "category": "Email Marketing",
    "score": 80.5,
    "price": "Free",
    "vendor": "Stability AI",
    "color": "oklch(0.4 0.2 119)",
    "website_url": ""
  },
  {
    "name": "AuraDeep 3",
    "category": "Business Strategy",
    "score": 87.5,
    "price": "$20/mo",
    "vendor": "SAP",
    "color": "oklch(0.7 0.1 143)",
    "website_url": ""
  },
  {
    "name": "NextHyper 7",
    "category": "Project Management",
    "score": 80.2,
    "price": "Enterprise",
    "vendor": "Inflection",
    "color": "oklch(0.8 0.1 190)",
    "website_url": ""
  },
  {
    "name": "VisionFlow 9",
    "category": "Brainstorming",
    "score": 74.5,
    "price": "Enterprise",
    "vendor": "Notion",
    "color": "oklch(0.4 0.1 60)",
    "website_url": ""
  },
  {
    "name": "VertexNode 2",
    "category": "Personal Growth",
    "score": 97.9,
    "price": "Free",
    "vendor": "Autodesk",
    "color": "oklch(0.7 0.2 190)",
    "website_url": ""
  },
  {
    "name": "MindGen 3",
    "category": "Gaming",
    "score": 95.1,
    "price": "Free",
    "vendor": "Microsoft",
    "color": "oklch(0.4 0.2 123)",
    "website_url": ""
  },
  {
    "name": "WiseOmni 5",
    "category": "Cybersecurity",
    "score": 71.9,
    "price": "$20/mo",
    "vendor": "Autodesk",
    "color": "oklch(0.6 0.2 12)",
    "website_url": ""
  },
  {
    "name": "PulseMind 2",
    "category": "DevOps",
    "score": 89.4,
    "price": "$20/mo",
    "vendor": "Notion",
    "color": "oklch(0.7 0.1 99)",
    "website_url": ""
  },
  {
    "name": "SynapseBase",
    "category": "Testing",
    "score": 87.5,
    "price": "$20/mo",
    "vendor": "xAI",
    "color": "oklch(0.5 0.1 181)",
    "website_url": ""
  },
  {
    "name": "VisionData 9",
    "category": "Translation",
    "score": 97.5,
    "price": "$20/mo",
    "vendor": "Inflection",
    "color": "oklch(0.8 0.2 121)",
    "website_url": ""
  },
  {
    "name": "DeepGen 9",
    "category": "3D Generation",
    "score": 94.2,
    "price": "$20/mo",
    "vendor": "Meta",
    "color": "oklch(0.4 0.2 148)",
    "website_url": ""
  },
  {
    "name": "BrainGPT 6",
    "category": "Robotics",
    "score": 95.3,
    "price": "$20/mo",
    "vendor": "AI21",
    "color": "oklch(0.8 0.1 351)",
    "website_url": ""
  },
  {
    "name": "HyperSmart 7",
    "category": "Agriculture",
    "score": 72.4,
    "price": "$20/mo",
    "vendor": "Cohere",
    "color": "oklch(0.5 0.2 53)",
    "website_url": ""
  },
  {
    "name": "MatrixLumina 9",
    "category": "Real Estate",
    "score": 87.7,
    "price": "$20/mo",
    "vendor": "xAI",
    "color": "oklch(0.6 0.1 175)",
    "website_url": ""
  },
  {
    "name": "OmniMatrix 2",
    "category": "Logistics",
    "score": 83.3,
    "price": "Free",
    "vendor": "Nvidia",
    "color": "oklch(0.8 0.1 124)",
    "website_url": ""
  },
  {
    "name": "TechAlpha 4",
    "category": "Manufacturing",
    "score": 74.9,
    "price": "Enterprise",
    "vendor": "Notion",
    "color": "oklch(0.6 0.1 194)",
    "website_url": ""
  },
  {
    "name": "SynapseLumina 7",
    "category": "Chatbots & Companions",
    "score": 87.2,
    "price": "Free",
    "vendor": "Nvidia",
    "color": "oklch(0.4 0.2 214)",
    "website_url": ""
  },
  {
    "name": "GridGrid 5",
    "category": "Coding & Development",
    "score": 76.9,
    "price": "Free",
    "vendor": "Nvidia",
    "color": "oklch(0.6 0.2 287)",
    "website_url": ""
  },
  {
    "name": "CoreVision 1",
    "category": "Enterprise Search",
    "score": 81.6,
    "price": "Enterprise",
    "vendor": "Google",
    "color": "oklch(0.4 0.2 2)",
    "website_url": ""
  },
  {
    "name": "LuminaData 6",
    "category": "Productivity & Workflows",
    "score": 98,
    "price": "Free",
    "vendor": "Baidu",
    "color": "oklch(0.5 0.2 235)",
    "website_url": ""
  },
  {
    "name": "SynthetixPulse 9",
    "category": "Video Generation",
    "score": 73.5,
    "price": "Free",
    "vendor": "Anthropic",
    "color": "oklch(0.4 0.1 29)",
    "website_url": ""
  },
  {
    "name": "MindGPT 9",
    "category": "Image Generation",
    "score": 79.3,
    "price": "Free",
    "vendor": "Meta",
    "color": "oklch(0.6 0.2 51)",
    "website_url": ""
  },
  {
    "name": "BotBase 4",
    "category": "Music & Audio",
    "score": 89.5,
    "price": "$20/mo",
    "vendor": "Adobe",
    "color": "oklch(0.4 0.2 254)",
    "website_url": ""
  },
  {
    "name": "SmartMeta",
    "category": "Meeting Assistants",
    "score": 72.1,
    "price": "Enterprise",
    "vendor": "AI21",
    "color": "oklch(0.5 0.1 34)",
    "website_url": ""
  },
  {
    "name": "SphereMatrix 3",
    "category": "Graphic Design",
    "score": 72.1,
    "price": "Free",
    "vendor": "IBM",
    "color": "oklch(0.5 0.1 46)",
    "website_url": ""
  },
  {
    "name": "MindPro 7",
    "category": "Voice Generation",
    "score": 77.9,
    "price": "Enterprise",
    "vendor": "Alibaba",
    "color": "oklch(0.4 0.1 283)",
    "website_url": ""
  },
  {
    "name": "MetaPro 2",
    "category": "App & Website Builders",
    "score": 79.1,
    "price": "Free",
    "vendor": "AWS",
    "color": "oklch(0.4 0.2 226)",
    "website_url": ""
  },
  {
    "name": "LinkFlow 4",
    "category": "Legal Tech",
    "score": 94.2,
    "price": "$20/mo",
    "vendor": "Google",
    "color": "oklch(0.4 0.2 187)",
    "website_url": ""
  },
  {
    "name": "DataCore 7",
    "category": "Healthcare",
    "score": 79.8,
    "price": "Free",
    "vendor": "Perplexity",
    "color": "oklch(0.7 0.2 89)",
    "website_url": ""
  },
  {
    "name": "DataEcho 7",
    "category": "Finance & Accounting",
    "score": 99,
    "price": "Free",
    "vendor": "AWS",
    "color": "oklch(0.4 0.1 217)",
    "website_url": ""
  },
  {
    "name": "WiseEcho 9",
    "category": "HR & Recruiting",
    "score": 95.7,
    "price": "Enterprise",
    "vendor": "xAI",
    "color": "oklch(0.7 0.1 251)",
    "website_url": ""
  },
  {
    "name": "OmniGen 5",
    "category": "Sales & CRM",
    "score": 73.4,
    "price": "Enterprise",
    "vendor": "ByteDance",
    "color": "oklch(0.5 0.2 146)",
    "website_url": ""
  },
  {
    "name": "PulseOmni 7",
    "category": "Content Marketing",
    "score": 72.9,
    "price": "Free",
    "vendor": "Oracle",
    "color": "oklch(0.4 0.2 32)",
    "website_url": ""
  },
  {
    "name": "LogicBase 7",
    "category": "Data Analysis",
    "score": 95.7,
    "price": "Free",
    "vendor": "AWS",
    "color": "oklch(0.4 0.1 144)",
    "website_url": ""
  },
  {
    "name": "SynthetixLink 3",
    "category": "Customer Support",
    "score": 86.7,
    "price": "$20/mo",
    "vendor": "Perplexity",
    "color": "oklch(0.8 0.2 255)",
    "website_url": ""
  },
  {
    "name": "MatrixBrain 6",
    "category": "Education",
    "score": 82.6,
    "price": "Free",
    "vendor": "Oracle",
    "color": "oklch(0.7 0.2 190)",
    "website_url": ""
  },
  {
    "name": "NovaNext 8",
    "category": "Research",
    "score": 73.3,
    "price": "$20/mo",
    "vendor": "Canva",
    "color": "oklch(0.7 0.2 192)",
    "website_url": ""
  },
  {
    "name": "DeepOmni 7",
    "category": "Copywriting",
    "score": 80.5,
    "price": "Enterprise",
    "vendor": "Alibaba",
    "color": "oklch(0.4 0.2 295)",
    "website_url": ""
  },
  {
    "name": "AuraData",
    "category": "SEO",
    "score": 75.6,
    "price": "Free",
    "vendor": "Notion",
    "color": "oklch(0.4 0.1 123)",
    "website_url": ""
  },
  {
    "name": "DataHub 7",
    "category": "Social Media",
    "score": 99.9,
    "price": "Free",
    "vendor": "Alibaba",
    "color": "oklch(0.6 0.2 304)",
    "website_url": ""
  },
  {
    "name": "MindMatrix 4",
    "category": "Email Marketing",
    "score": 91.4,
    "price": "$20/mo",
    "vendor": "xAI",
    "color": "oklch(0.7 0.1 129)",
    "website_url": ""
  },
  {
    "name": "LinkBot 3",
    "category": "Business Strategy",
    "score": 85.9,
    "price": "$20/mo",
    "vendor": "HuggingFace",
    "color": "oklch(0.4 0.2 201)",
    "website_url": ""
  },
  {
    "name": "WaveOmni 4",
    "category": "Brainstorming",
    "score": 97.4,
    "price": "Enterprise",
    "vendor": "Perplexity",
    "color": "oklch(0.6 0.2 267)",
    "website_url": ""
  },
  {
    "name": "EchoDeep 5",
    "category": "Personal Growth",
    "score": 96.3,
    "price": "Enterprise",
    "vendor": "Oracle",
    "color": "oklch(0.6 0.1 142)",
    "website_url": ""
  },
  {
    "name": "SynthetixNexus 8",
    "category": "Gaming",
    "score": 89.2,
    "price": "$20/mo",
    "vendor": "Mistral",
    "color": "oklch(0.5 0.1 255)",
    "website_url": ""
  },
  {
    "name": "QuantumHub 4",
    "category": "Cybersecurity",
    "score": 81.5,
    "price": "Enterprise",
    "vendor": "Inflection",
    "color": "oklch(0.4 0.1 198)",
    "website_url": ""
  },
  {
    "name": "WiseLink 4",
    "category": "DevOps",
    "score": 83.9,
    "price": "Enterprise",
    "vendor": "Cohere",
    "color": "oklch(0.6 0.1 14)",
    "website_url": ""
  },
  {
    "name": "PulseNext 3",
    "category": "Testing",
    "score": 73.6,
    "price": "$20/mo",
    "vendor": "IBM",
    "color": "oklch(0.4 0.2 40)",
    "website_url": ""
  },
  {
    "name": "DataSync 3",
    "category": "Translation",
    "score": 97.2,
    "price": "$20/mo",
    "vendor": "Alibaba",
    "color": "oklch(0.5 0.2 119)",
    "website_url": ""
  },
  {
    "name": "MetaBot 7",
    "category": "3D Generation",
    "score": 90.3,
    "price": "Enterprise",
    "vendor": "Alibaba",
    "color": "oklch(0.7 0.1 330)",
    "website_url": ""
  },
  {
    "name": "AutoSync 3",
    "category": "Robotics",
    "score": 83.4,
    "price": "Free",
    "vendor": "ByteDance",
    "color": "oklch(0.5 0.2 187)",
    "website_url": ""
  },
  {
    "name": "SyncNode 5",
    "category": "Agriculture",
    "score": 88.3,
    "price": "Free",
    "vendor": "Microsoft",
    "color": "oklch(0.4 0.2 153)",
    "website_url": ""
  },
  {
    "name": "CloudSpark 5",
    "category": "Real Estate",
    "score": 86,
    "price": "Free",
    "vendor": "Notion",
    "color": "oklch(0.6 0.2 313)",
    "website_url": ""
  },
  {
    "name": "SynthetixMatrix 4",
    "category": "Logistics",
    "score": 85.1,
    "price": "$20/mo",
    "vendor": "SAP",
    "color": "oklch(0.4 0.1 128)",
    "website_url": ""
  },
  {
    "name": "OmniWise 6",
    "category": "Manufacturing",
    "score": 98.3,
    "price": "$20/mo",
    "vendor": "Google",
    "color": "oklch(0.5 0.2 171)",
    "website_url": ""
  },
  {
    "name": "ProPulse",
    "category": "Chatbots & Companions",
    "score": 83.5,
    "price": "Enterprise",
    "vendor": "Inflection",
    "color": "oklch(0.8 0.2 29)",
    "website_url": ""
  },
  {
    "name": "TechLogic 6",
    "category": "Enterprise Search",
    "score": 72.7,
    "price": "Enterprise",
    "vendor": "IBM",
    "color": "oklch(0.7 0.1 120)",
    "website_url": ""
  },
  {
    "name": "TechPulse",
    "category": "Productivity & Workflows",
    "score": 94.5,
    "price": "Enterprise",
    "vendor": "Stability AI",
    "color": "oklch(0.6 0.2 127)",
    "website_url": ""
  },
  {
    "name": "DeepCloud 2",
    "category": "Video Generation",
    "score": 95.2,
    "price": "Free",
    "vendor": "Perplexity",
    "color": "oklch(0.4 0.2 188)",
    "website_url": ""
  },
  {
    "name": "TechMatrix 3",
    "category": "Image Generation",
    "score": 80.7,
    "price": "Enterprise",
    "vendor": "AI21",
    "color": "oklch(0.5 0.1 207)",
    "website_url": ""
  },
  {
    "name": "SphereOmni 4",
    "category": "Music & Audio",
    "score": 86,
    "price": "Free",
    "vendor": "Adobe",
    "color": "oklch(0.8 0.1 346)",
    "website_url": ""
  },
  {
    "name": "CyberTech 1",
    "category": "Meeting Assistants",
    "score": 92.7,
    "price": "$20/mo",
    "vendor": "Adobe",
    "color": "oklch(0.4 0.1 304)",
    "website_url": ""
  },
  {
    "name": "HyperBrain 6",
    "category": "Graphic Design",
    "score": 86.5,
    "price": "Free",
    "vendor": "IBM",
    "color": "oklch(0.5 0.1 194)",
    "website_url": ""
  },
  {
    "name": "NovaWise 9",
    "category": "Voice Generation",
    "score": 94.9,
    "price": "$20/mo",
    "vendor": "SAP",
    "color": "oklch(0.8 0.2 136)",
    "website_url": ""
  },
  {
    "name": "DeepData 2",
    "category": "App & Website Builders",
    "score": 86.7,
    "price": "Enterprise",
    "vendor": "Apple",
    "color": "oklch(0.6 0.2 294)",
    "website_url": ""
  },
  {
    "name": "MatrixMind 4",
    "category": "Legal Tech",
    "score": 97.1,
    "price": "Free",
    "vendor": "Alibaba",
    "color": "oklch(0.7 0.1 18)",
    "website_url": ""
  },
  {
    "name": "FlowSpark 7",
    "category": "Healthcare",
    "score": 85.8,
    "price": "Free",
    "vendor": "xAI",
    "color": "oklch(0.6 0.2 87)",
    "website_url": ""
  },
  {
    "name": "VisionSpark 7",
    "category": "Finance & Accounting",
    "score": 75.3,
    "price": "Free",
    "vendor": "Microsoft",
    "color": "oklch(0.5 0.1 349)",
    "website_url": ""
  },
  {
    "name": "SphereTech",
    "category": "HR & Recruiting",
    "score": 84.1,
    "price": "Enterprise",
    "vendor": "Anthropic",
    "color": "oklch(0.7 0.2 145)",
    "website_url": ""
  },
  {
    "name": "HyperMeta 6",
    "category": "Sales & CRM",
    "score": 93.6,
    "price": "Free",
    "vendor": "Google",
    "color": "oklch(0.6 0.1 332)",
    "website_url": ""
  },
  {
    "name": "EchoVertex 6",
    "category": "Content Marketing",
    "score": 74.3,
    "price": "Enterprise",
    "vendor": "Canva",
    "color": "oklch(0.6 0.1 193)",
    "website_url": ""
  },
  {
    "name": "SmartNexus 1",
    "category": "Data Analysis",
    "score": 92.3,
    "price": "$20/mo",
    "vendor": "AI21",
    "color": "oklch(0.6 0.2 356)",
    "website_url": ""
  },
  {
    "name": "CloudPro 1",
    "category": "Customer Support",
    "score": 76,
    "price": "Enterprise",
    "vendor": "ByteDance",
    "color": "oklch(0.4 0.2 28)",
    "website_url": ""
  },
  {
    "name": "LogicTech 9",
    "category": "Education",
    "score": 81.2,
    "price": "Free",
    "vendor": "Apple",
    "color": "oklch(0.4 0.1 351)",
    "website_url": ""
  },
  {
    "name": "CoreAlpha 6",
    "category": "Research",
    "score": 77.3,
    "price": "$20/mo",
    "vendor": "Inflection",
    "color": "oklch(0.7 0.2 260)",
    "website_url": ""
  },
  {
    "name": "NexusNode 1",
    "category": "Copywriting",
    "score": 84.6,
    "price": "$20/mo",
    "vendor": "Salesforce",
    "color": "oklch(0.6 0.1 326)",
    "website_url": ""
  },
  {
    "name": "VisionVertex",
    "category": "SEO",
    "score": 79.7,
    "price": "Free",
    "vendor": "Salesforce",
    "color": "oklch(0.8 0.2 257)",
    "website_url": ""
  },
  {
    "name": "DeepCloud 6",
    "category": "Social Media",
    "score": 86.6,
    "price": "$20/mo",
    "vendor": "SAP",
    "color": "oklch(0.6 0.1 281)",
    "website_url": ""
  },
  {
    "name": "MindLink 2",
    "category": "Email Marketing",
    "score": 84.2,
    "price": "Enterprise",
    "vendor": "Baidu",
    "color": "oklch(0.6 0.2 113)",
    "website_url": ""
  },
  {
    "name": "SynthetixMeta",
    "category": "Project Management",
    "score": 77.3,
    "price": "$20/mo",
    "vendor": "Anthropic",
    "color": "oklch(0.5 0.1 293)",
    "website_url": ""
  },
  {
    "name": "AlphaHyper 5",
    "category": "Brainstorming",
    "score": 79.2,
    "price": "Free",
    "vendor": "Tencent",
    "color": "oklch(0.6 0.1 119)",
    "website_url": ""
  },
  {
    "name": "DataPulse 6",
    "category": "Personal Growth",
    "score": 93.6,
    "price": "Enterprise",
    "vendor": "Mistral",
    "color": "oklch(0.7 0.1 63)",
    "website_url": ""
  },
  {
    "name": "VertexGen 1",
    "category": "Gaming",
    "score": 72.9,
    "price": "$20/mo",
    "vendor": "Tencent",
    "color": "oklch(0.6 0.1 146)",
    "website_url": ""
  },
  {
    "name": "SparkMatrix 4",
    "category": "Cybersecurity",
    "score": 91,
    "price": "Enterprise",
    "vendor": "Google",
    "color": "oklch(0.5 0.1 25)",
    "website_url": ""
  },
  {
    "name": "NextSmart 8",
    "category": "DevOps",
    "score": 71.5,
    "price": "Free",
    "vendor": "Nvidia",
    "color": "oklch(0.5 0.2 62)",
    "website_url": ""
  },
  {
    "name": "VertexWave 9",
    "category": "Testing",
    "score": 71.9,
    "price": "Enterprise",
    "vendor": "Microsoft",
    "color": "oklch(0.4 0.1 273)",
    "website_url": ""
  },
  {
    "name": "EchoPro 9",
    "category": "Translation",
    "score": 81.2,
    "price": "Enterprise",
    "vendor": "Nvidia",
    "color": "oklch(0.5 0.1 316)",
    "website_url": ""
  },
  {
    "name": "EchoGen 5",
    "category": "3D Generation",
    "score": 82.5,
    "price": "Free",
    "vendor": "Notion",
    "color": "oklch(0.8 0.1 299)",
    "website_url": ""
  },
  {
    "name": "CoreNode 6",
    "category": "Robotics",
    "score": 79.3,
    "price": "Enterprise",
    "vendor": "SAP",
    "color": "oklch(0.7 0.1 80)",
    "website_url": ""
  },
  {
    "name": "SynapsePulse 6",
    "category": "Agriculture",
    "score": 97.2,
    "price": "Free",
    "vendor": "Cohere",
    "color": "oklch(0.6 0.2 320)",
    "website_url": ""
  },
  {
    "name": "CoreGPT 4",
    "category": "Real Estate",
    "score": 84.2,
    "price": "$20/mo",
    "vendor": "Tencent",
    "color": "oklch(0.7 0.2 296)",
    "website_url": ""
  },
  {
    "name": "GridNode 8",
    "category": "Logistics",
    "score": 87.7,
    "price": "Free",
    "vendor": "Nvidia",
    "color": "oklch(0.6 0.1 265)",
    "website_url": ""
  },
  {
    "name": "DataNova 9",
    "category": "Manufacturing",
    "score": 88.1,
    "price": "$20/mo",
    "vendor": "IBM",
    "color": "oklch(0.8 0.2 211)",
    "website_url": ""
  }
];
