/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerifyEmailRouteImport } from './routes/verify-email'
import { Route as UnsubscribeRouteImport } from './routes/unsubscribe'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RankingsRouteImport } from './routes/rankings'
import { Route as PromptsRouteImport } from './routes/prompts'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as NewsRouteImport } from './routes/news'
import { Route as LoginRouteImport } from './routes/login'
import { Route as HelpRouteImport } from './routes/help'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as FinderRouteImport } from './routes/finder'
import { Route as FeedbackRouteImport } from './routes/feedback'
import { Route as CompareRouteImport } from './routes/compare'
import { Route as CalculatorRouteImport } from './routes/calculator'
import { Route as BillingRouteImport } from './routes/billing'
import { Route as AuthCallbackRouteImport } from './routes/auth-callback'
import { Route as AppBuildersRouteImport } from './routes/app-builders'
import { Route as AgentsRouteImport } from './routes/agents'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AccountRouteImport } from './routes/account'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StacksIndexRouteImport } from './routes/stacks.index'
import { Route as LegalIndexRouteImport } from './routes/legal/index'
import { Route as StacksIdRouteImport } from './routes/stacks.$id'
import { Route as RefCodeRouteImport } from './routes/ref.$code'
import { Route as LegalTermsRouteImport } from './routes/legal.terms'
import { Route as LegalPrivacyRouteImport } from './routes/legal.privacy'
import { Route as LegalDisclaimerRouteImport } from './routes/legal.disclaimer'
import { Route as LegalTypeRouteImport } from './routes/legal/$type'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as AuthVerifyEmailRouteImport } from './routes/auth/verify-email'
import { Route as AuthRegisterRouteImport } from './routes/auth/register'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as AuthForgotPasswordRouteImport } from './routes/auth/forgot-password'
import { Route as AdminToolsRouteImport } from './routes/admin.tools'
import { Route as AdminSupportCenterRouteImport } from './routes/admin.support-center'
import { Route as AdminSupportRouteImport } from './routes/admin.support'
import { Route as AdminRevenueRouteImport } from './routes/admin.revenue'
import { Route as AdminPublicStacksRouteImport } from './routes/admin.public-stacks'
import { Route as AdminPerformanceRouteImport } from './routes/admin.performance'
import { Route as AdminMonitoringRouteImport } from './routes/admin.monitoring'
import { Route as AdminMarketIntelligenceRouteImport } from './routes/admin.market-intelligence'
import { Route as AdminLegalDocumentsRouteImport } from './routes/admin.legal-documents'
import { Route as AdminLegalRouteImport } from './routes/admin/legal'
import { Route as AdminIntelligenceRouteImport } from './routes/admin.intelligence'
import { Route as AdminHelpCenterRouteImport } from './routes/admin/help-center'
import { Route as AdminChangelogRouteImport } from './routes/admin/changelog'
import { Route as AdminAuthDiagnosticsRouteImport } from './routes/admin.auth-diagnostics'
import { Route as AdminAnalyticsRouteImport } from './routes/admin.analytics'
import { Route as AccountSupportRouteImport } from './routes/account.support'
import { Route as AccountRequestsRouteImport } from './routes/account.requests'
import { Route as AdminLegalPrivacyRouteImport } from './routes/admin/legal/privacy'
import { Route as AccountRequestsIdRouteImport } from './routes/account.requests.$id'

const VerifyEmailRoute = VerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const UnsubscribeRoute = UnsubscribeRouteImport.update({
  id: '/unsubscribe',
  path: '/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RankingsRoute = RankingsRouteImport.update({
  id: '/rankings',
  path: '/rankings',
  getParentRoute: () => rootRouteImport,
} as any)
const PromptsRoute = PromptsRouteImport.update({
  id: '/prompts',
  path: '/prompts',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsRoute = NewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpRoute = HelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const FinderRoute = FinderRouteImport.update({
  id: '/finder',
  path: '/finder',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedbackRoute = FeedbackRouteImport.update({
  id: '/feedback',
  path: '/feedback',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareRoute = CompareRouteImport.update({
  id: '/compare',
  path: '/compare',
  getParentRoute: () => rootRouteImport,
} as any)
const CalculatorRoute = CalculatorRouteImport.update({
  id: '/calculator',
  path: '/calculator',
  getParentRoute: () => rootRouteImport,
} as any)
const BillingRoute = BillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth-callback',
  path: '/auth-callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AppBuildersRoute = AppBuildersRouteImport.update({
  id: '/app-builders',
  path: '/app-builders',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsRoute = AgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StacksIndexRoute = StacksIndexRouteImport.update({
  id: '/stacks/',
  path: '/stacks/',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalIndexRoute = LegalIndexRouteImport.update({
  id: '/legal/',
  path: '/legal/',
  getParentRoute: () => rootRouteImport,
} as any)
const StacksIdRoute = StacksIdRouteImport.update({
  id: '/stacks/$id',
  path: '/stacks/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const RefCodeRoute = RefCodeRouteImport.update({
  id: '/ref/$code',
  path: '/ref/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalTermsRoute = LegalTermsRouteImport.update({
  id: '/legal/terms',
  path: '/legal/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalPrivacyRoute = LegalPrivacyRouteImport.update({
  id: '/legal/privacy',
  path: '/legal/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalDisclaimerRoute = LegalDisclaimerRouteImport.update({
  id: '/legal/disclaimer',
  path: '/legal/disclaimer',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalTypeRoute = LegalTypeRouteImport.update({
  id: '/legal/$type',
  path: '/legal/$type',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthVerifyEmailRoute = AuthVerifyEmailRouteImport.update({
  id: '/auth/verify-email',
  path: '/auth/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/auth/register',
  path: '/auth/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/auth/forgot-password',
  path: '/auth/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminToolsRoute = AdminToolsRouteImport.update({
  id: '/tools',
  path: '/tools',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSupportCenterRoute = AdminSupportCenterRouteImport.update({
  id: '/support-center',
  path: '/support-center',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSupportRoute = AdminSupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRevenueRoute = AdminRevenueRouteImport.update({
  id: '/revenue',
  path: '/revenue',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPublicStacksRoute = AdminPublicStacksRouteImport.update({
  id: '/public-stacks',
  path: '/public-stacks',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPerformanceRoute = AdminPerformanceRouteImport.update({
  id: '/performance',
  path: '/performance',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMonitoringRoute = AdminMonitoringRouteImport.update({
  id: '/monitoring',
  path: '/monitoring',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMarketIntelligenceRoute = AdminMarketIntelligenceRouteImport.update({
  id: '/market-intelligence',
  path: '/market-intelligence',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLegalDocumentsRoute = AdminLegalDocumentsRouteImport.update({
  id: '/legal-documents',
  path: '/legal-documents',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLegalRoute = AdminLegalRouteImport.update({
  id: '/legal',
  path: '/legal',
  getParentRoute: () => AdminRoute,
} as any)
const AdminIntelligenceRoute = AdminIntelligenceRouteImport.update({
  id: '/intelligence',
  path: '/intelligence',
  getParentRoute: () => AdminRoute,
} as any)
const AdminHelpCenterRoute = AdminHelpCenterRouteImport.update({
  id: '/help-center',
  path: '/help-center',
  getParentRoute: () => AdminRoute,
} as any)
const AdminChangelogRoute = AdminChangelogRouteImport.update({
  id: '/changelog',
  path: '/changelog',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAuthDiagnosticsRoute = AdminAuthDiagnosticsRouteImport.update({
  id: '/auth-diagnostics',
  path: '/auth-diagnostics',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAnalyticsRoute = AdminAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AdminRoute,
} as any)
const AccountSupportRoute = AccountSupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => AccountRoute,
} as any)
const AccountRequestsRoute = AccountRequestsRouteImport.update({
  id: '/requests',
  path: '/requests',
  getParentRoute: () => AccountRoute,
} as any)
const AdminLegalPrivacyRoute = AdminLegalPrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => AdminLegalRoute,
} as any)
const AccountRequestsIdRoute = AccountRequestsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AccountRequestsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRouteWithChildren
  '/admin': typeof AdminRouteWithChildren
  '/agents': typeof AgentsRoute
  '/app-builders': typeof AppBuildersRoute
  '/auth-callback': typeof AuthCallbackRoute
  '/billing': typeof BillingRoute
  '/calculator': typeof CalculatorRoute
  '/compare': typeof CompareRoute
  '/feedback': typeof FeedbackRoute
  '/finder': typeof FinderRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/help': typeof HelpRoute
  '/login': typeof LoginRoute
  '/news': typeof NewsRoute
  '/onboarding': typeof OnboardingRoute
  '/profile': typeof ProfileRoute
  '/prompts': typeof PromptsRoute
  '/rankings': typeof RankingsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/verify-email': typeof VerifyEmailRoute
  '/account/requests': typeof AccountRequestsRouteWithChildren
  '/account/support': typeof AccountSupportRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/auth-diagnostics': typeof AdminAuthDiagnosticsRoute
  '/admin/changelog': typeof AdminChangelogRoute
  '/admin/help-center': typeof AdminHelpCenterRoute
  '/admin/intelligence': typeof AdminIntelligenceRoute
  '/admin/legal': typeof AdminLegalRouteWithChildren
  '/admin/legal-documents': typeof AdminLegalDocumentsRoute
  '/admin/market-intelligence': typeof AdminMarketIntelligenceRoute
  '/admin/monitoring': typeof AdminMonitoringRoute
  '/admin/performance': typeof AdminPerformanceRoute
  '/admin/public-stacks': typeof AdminPublicStacksRoute
  '/admin/revenue': typeof AdminRevenueRoute
  '/admin/support': typeof AdminSupportRoute
  '/admin/support-center': typeof AdminSupportCenterRoute
  '/admin/tools': typeof AdminToolsRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/auth/verify-email': typeof AuthVerifyEmailRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/legal/$type': typeof LegalTypeRoute
  '/legal/disclaimer': typeof LegalDisclaimerRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/terms': typeof LegalTermsRoute
  '/ref/$code': typeof RefCodeRoute
  '/stacks/$id': typeof StacksIdRoute
  '/legal/': typeof LegalIndexRoute
  '/stacks/': typeof StacksIndexRoute
  '/account/requests/$id': typeof AccountRequestsIdRoute
  '/admin/legal/privacy': typeof AdminLegalPrivacyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRouteWithChildren
  '/admin': typeof AdminRouteWithChildren
  '/agents': typeof AgentsRoute
  '/app-builders': typeof AppBuildersRoute
  '/auth-callback': typeof AuthCallbackRoute
  '/billing': typeof BillingRoute
  '/calculator': typeof CalculatorRoute
  '/compare': typeof CompareRoute
  '/feedback': typeof FeedbackRoute
  '/finder': typeof FinderRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/help': typeof HelpRoute
  '/login': typeof LoginRoute
  '/news': typeof NewsRoute
  '/onboarding': typeof OnboardingRoute
  '/profile': typeof ProfileRoute
  '/prompts': typeof PromptsRoute
  '/rankings': typeof RankingsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/verify-email': typeof VerifyEmailRoute
  '/account/requests': typeof AccountRequestsRouteWithChildren
  '/account/support': typeof AccountSupportRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/auth-diagnostics': typeof AdminAuthDiagnosticsRoute
  '/admin/changelog': typeof AdminChangelogRoute
  '/admin/help-center': typeof AdminHelpCenterRoute
  '/admin/intelligence': typeof AdminIntelligenceRoute
  '/admin/legal': typeof AdminLegalRouteWithChildren
  '/admin/legal-documents': typeof AdminLegalDocumentsRoute
  '/admin/market-intelligence': typeof AdminMarketIntelligenceRoute
  '/admin/monitoring': typeof AdminMonitoringRoute
  '/admin/performance': typeof AdminPerformanceRoute
  '/admin/public-stacks': typeof AdminPublicStacksRoute
  '/admin/revenue': typeof AdminRevenueRoute
  '/admin/support': typeof AdminSupportRoute
  '/admin/support-center': typeof AdminSupportCenterRoute
  '/admin/tools': typeof AdminToolsRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/auth/verify-email': typeof AuthVerifyEmailRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/legal/$type': typeof LegalTypeRoute
  '/legal/disclaimer': typeof LegalDisclaimerRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/terms': typeof LegalTermsRoute
  '/ref/$code': typeof RefCodeRoute
  '/stacks/$id': typeof StacksIdRoute
  '/legal': typeof LegalIndexRoute
  '/stacks': typeof StacksIndexRoute
  '/account/requests/$id': typeof AccountRequestsIdRoute
  '/admin/legal/privacy': typeof AdminLegalPrivacyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRouteWithChildren
  '/admin': typeof AdminRouteWithChildren
  '/agents': typeof AgentsRoute
  '/app-builders': typeof AppBuildersRoute
  '/auth-callback': typeof AuthCallbackRoute
  '/billing': typeof BillingRoute
  '/calculator': typeof CalculatorRoute
  '/compare': typeof CompareRoute
  '/feedback': typeof FeedbackRoute
  '/finder': typeof FinderRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/help': typeof HelpRoute
  '/login': typeof LoginRoute
  '/news': typeof NewsRoute
  '/onboarding': typeof OnboardingRoute
  '/profile': typeof ProfileRoute
  '/prompts': typeof PromptsRoute
  '/rankings': typeof RankingsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/verify-email': typeof VerifyEmailRoute
  '/account/requests': typeof AccountRequestsRouteWithChildren
  '/account/support': typeof AccountSupportRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/auth-diagnostics': typeof AdminAuthDiagnosticsRoute
  '/admin/changelog': typeof AdminChangelogRoute
  '/admin/help-center': typeof AdminHelpCenterRoute
  '/admin/intelligence': typeof AdminIntelligenceRoute
  '/admin/legal': typeof AdminLegalRouteWithChildren
  '/admin/legal-documents': typeof AdminLegalDocumentsRoute
  '/admin/market-intelligence': typeof AdminMarketIntelligenceRoute
  '/admin/monitoring': typeof AdminMonitoringRoute
  '/admin/performance': typeof AdminPerformanceRoute
  '/admin/public-stacks': typeof AdminPublicStacksRoute
  '/admin/revenue': typeof AdminRevenueRoute
  '/admin/support': typeof AdminSupportRoute
  '/admin/support-center': typeof AdminSupportCenterRoute
  '/admin/tools': typeof AdminToolsRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/auth/verify-email': typeof AuthVerifyEmailRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/legal/$type': typeof LegalTypeRoute
  '/legal/disclaimer': typeof LegalDisclaimerRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/terms': typeof LegalTermsRoute
  '/ref/$code': typeof RefCodeRoute
  '/stacks/$id': typeof StacksIdRoute
  '/legal/': typeof LegalIndexRoute
  '/stacks/': typeof StacksIndexRoute
  '/account/requests/$id': typeof AccountRequestsIdRoute
  '/admin/legal/privacy': typeof AdminLegalPrivacyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/account'
    | '/admin'
    | '/agents'
    | '/app-builders'
    | '/auth-callback'
    | '/billing'
    | '/calculator'
    | '/compare'
    | '/feedback'
    | '/finder'
    | '/forgot-password'
    | '/help'
    | '/login'
    | '/news'
    | '/onboarding'
    | '/profile'
    | '/prompts'
    | '/rankings'
    | '/reset-password'
    | '/settings'
    | '/signup'
    | '/unsubscribe'
    | '/verify-email'
    | '/account/requests'
    | '/account/support'
    | '/admin/analytics'
    | '/admin/auth-diagnostics'
    | '/admin/changelog'
    | '/admin/help-center'
    | '/admin/intelligence'
    | '/admin/legal'
    | '/admin/legal-documents'
    | '/admin/market-intelligence'
    | '/admin/monitoring'
    | '/admin/performance'
    | '/admin/public-stacks'
    | '/admin/revenue'
    | '/admin/support'
    | '/admin/support-center'
    | '/admin/tools'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/register'
    | '/auth/verify-email'
    | '/blog/$slug'
    | '/legal/$type'
    | '/legal/disclaimer'
    | '/legal/privacy'
    | '/legal/terms'
    | '/ref/$code'
    | '/stacks/$id'
    | '/legal/'
    | '/stacks/'
    | '/account/requests/$id'
    | '/admin/legal/privacy'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/account'
    | '/admin'
    | '/agents'
    | '/app-builders'
    | '/auth-callback'
    | '/billing'
    | '/calculator'
    | '/compare'
    | '/feedback'
    | '/finder'
    | '/forgot-password'
    | '/help'
    | '/login'
    | '/news'
    | '/onboarding'
    | '/profile'
    | '/prompts'
    | '/rankings'
    | '/reset-password'
    | '/settings'
    | '/signup'
    | '/unsubscribe'
    | '/verify-email'
    | '/account/requests'
    | '/account/support'
    | '/admin/analytics'
    | '/admin/auth-diagnostics'
    | '/admin/changelog'
    | '/admin/help-center'
    | '/admin/intelligence'
    | '/admin/legal'
    | '/admin/legal-documents'
    | '/admin/market-intelligence'
    | '/admin/monitoring'
    | '/admin/performance'
    | '/admin/public-stacks'
    | '/admin/revenue'
    | '/admin/support'
    | '/admin/support-center'
    | '/admin/tools'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/register'
    | '/auth/verify-email'
    | '/blog/$slug'
    | '/legal/$type'
    | '/legal/disclaimer'
    | '/legal/privacy'
    | '/legal/terms'
    | '/ref/$code'
    | '/stacks/$id'
    | '/legal'
    | '/stacks'
    | '/account/requests/$id'
    | '/admin/legal/privacy'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/account'
    | '/admin'
    | '/agents'
    | '/app-builders'
    | '/auth-callback'
    | '/billing'
    | '/calculator'
    | '/compare'
    | '/feedback'
    | '/finder'
    | '/forgot-password'
    | '/help'
    | '/login'
    | '/news'
    | '/onboarding'
    | '/profile'
    | '/prompts'
    | '/rankings'
    | '/reset-password'
    | '/settings'
    | '/signup'
    | '/unsubscribe'
    | '/verify-email'
    | '/account/requests'
    | '/account/support'
    | '/admin/analytics'
    | '/admin/auth-diagnostics'
    | '/admin/changelog'
    | '/admin/help-center'
    | '/admin/intelligence'
    | '/admin/legal'
    | '/admin/legal-documents'
    | '/admin/market-intelligence'
    | '/admin/monitoring'
    | '/admin/performance'
    | '/admin/public-stacks'
    | '/admin/revenue'
    | '/admin/support'
    | '/admin/support-center'
    | '/admin/tools'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/register'
    | '/auth/verify-email'
    | '/blog/$slug'
    | '/legal/$type'
    | '/legal/disclaimer'
    | '/legal/privacy'
    | '/legal/terms'
    | '/ref/$code'
    | '/stacks/$id'
    | '/legal/'
    | '/stacks/'
    | '/account/requests/$id'
    | '/admin/legal/privacy'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AccountRoute: typeof AccountRouteWithChildren
  AdminRoute: typeof AdminRouteWithChildren
  AgentsRoute: typeof AgentsRoute
  AppBuildersRoute: typeof AppBuildersRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  BillingRoute: typeof BillingRoute
  CalculatorRoute: typeof CalculatorRoute
  CompareRoute: typeof CompareRoute
  FeedbackRoute: typeof FeedbackRoute
  FinderRoute: typeof FinderRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  HelpRoute: typeof HelpRoute
  LoginRoute: typeof LoginRoute
  NewsRoute: typeof NewsRoute
  OnboardingRoute: typeof OnboardingRoute
  ProfileRoute: typeof ProfileRoute
  PromptsRoute: typeof PromptsRoute
  RankingsRoute: typeof RankingsRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SettingsRoute: typeof SettingsRoute
  SignupRoute: typeof SignupRoute
  UnsubscribeRoute: typeof UnsubscribeRoute
  VerifyEmailRoute: typeof VerifyEmailRoute
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
  AuthVerifyEmailRoute: typeof AuthVerifyEmailRoute
  BlogSlugRoute: typeof BlogSlugRoute
  LegalTypeRoute: typeof LegalTypeRoute
  LegalDisclaimerRoute: typeof LegalDisclaimerRoute
  LegalPrivacyRoute: typeof LegalPrivacyRoute
  LegalTermsRoute: typeof LegalTermsRoute
  RefCodeRoute: typeof RefCodeRoute
  StacksIdRoute: typeof StacksIdRoute
  LegalIndexRoute: typeof LegalIndexRoute
  StacksIndexRoute: typeof StacksIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verify-email': {
      id: '/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof VerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/unsubscribe': {
      id: '/unsubscribe'
      path: '/unsubscribe'
      fullPath: '/unsubscribe'
      preLoaderRoute: typeof UnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rankings': {
      id: '/rankings'
      path: '/rankings'
      fullPath: '/rankings'
      preLoaderRoute: typeof RankingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prompts': {
      id: '/prompts'
      path: '/prompts'
      fullPath: '/prompts'
      preLoaderRoute: typeof PromptsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news': {
      id: '/news'
      path: '/news'
      fullPath: '/news'
      preLoaderRoute: typeof NewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help': {
      id: '/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof HelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/finder': {
      id: '/finder'
      path: '/finder'
      fullPath: '/finder'
      preLoaderRoute: typeof FinderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feedback': {
      id: '/feedback'
      path: '/feedback'
      fullPath: '/feedback'
      preLoaderRoute: typeof FeedbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare': {
      id: '/compare'
      path: '/compare'
      fullPath: '/compare'
      preLoaderRoute: typeof CompareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calculator': {
      id: '/calculator'
      path: '/calculator'
      fullPath: '/calculator'
      preLoaderRoute: typeof CalculatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/billing': {
      id: '/billing'
      path: '/billing'
      fullPath: '/billing'
      preLoaderRoute: typeof BillingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth-callback': {
      id: '/auth-callback'
      path: '/auth-callback'
      fullPath: '/auth-callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app-builders': {
      id: '/app-builders'
      path: '/app-builders'
      fullPath: '/app-builders'
      preLoaderRoute: typeof AppBuildersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents': {
      id: '/agents'
      path: '/agents'
      fullPath: '/agents'
      preLoaderRoute: typeof AgentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stacks/': {
      id: '/stacks/'
      path: '/stacks'
      fullPath: '/stacks/'
      preLoaderRoute: typeof StacksIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/': {
      id: '/legal/'
      path: '/legal'
      fullPath: '/legal/'
      preLoaderRoute: typeof LegalIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stacks/$id': {
      id: '/stacks/$id'
      path: '/stacks/$id'
      fullPath: '/stacks/$id'
      preLoaderRoute: typeof StacksIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ref/$code': {
      id: '/ref/$code'
      path: '/ref/$code'
      fullPath: '/ref/$code'
      preLoaderRoute: typeof RefCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/terms': {
      id: '/legal/terms'
      path: '/legal/terms'
      fullPath: '/legal/terms'
      preLoaderRoute: typeof LegalTermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/privacy': {
      id: '/legal/privacy'
      path: '/legal/privacy'
      fullPath: '/legal/privacy'
      preLoaderRoute: typeof LegalPrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/disclaimer': {
      id: '/legal/disclaimer'
      path: '/legal/disclaimer'
      fullPath: '/legal/disclaimer'
      preLoaderRoute: typeof LegalDisclaimerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/$type': {
      id: '/legal/$type'
      path: '/legal/$type'
      fullPath: '/legal/$type'
      preLoaderRoute: typeof LegalTypeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/verify-email': {
      id: '/auth/verify-email'
      path: '/auth/verify-email'
      fullPath: '/auth/verify-email'
      preLoaderRoute: typeof AuthVerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/register': {
      id: '/auth/register'
      path: '/auth/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/forgot-password': {
      id: '/auth/forgot-password'
      path: '/auth/forgot-password'
      fullPath: '/auth/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/tools': {
      id: '/admin/tools'
      path: '/tools'
      fullPath: '/admin/tools'
      preLoaderRoute: typeof AdminToolsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/support-center': {
      id: '/admin/support-center'
      path: '/support-center'
      fullPath: '/admin/support-center'
      preLoaderRoute: typeof AdminSupportCenterRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/support': {
      id: '/admin/support'
      path: '/support'
      fullPath: '/admin/support'
      preLoaderRoute: typeof AdminSupportRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/revenue': {
      id: '/admin/revenue'
      path: '/revenue'
      fullPath: '/admin/revenue'
      preLoaderRoute: typeof AdminRevenueRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/public-stacks': {
      id: '/admin/public-stacks'
      path: '/public-stacks'
      fullPath: '/admin/public-stacks'
      preLoaderRoute: typeof AdminPublicStacksRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/performance': {
      id: '/admin/performance'
      path: '/performance'
      fullPath: '/admin/performance'
      preLoaderRoute: typeof AdminPerformanceRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/monitoring': {
      id: '/admin/monitoring'
      path: '/monitoring'
      fullPath: '/admin/monitoring'
      preLoaderRoute: typeof AdminMonitoringRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/market-intelligence': {
      id: '/admin/market-intelligence'
      path: '/market-intelligence'
      fullPath: '/admin/market-intelligence'
      preLoaderRoute: typeof AdminMarketIntelligenceRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/legal-documents': {
      id: '/admin/legal-documents'
      path: '/legal-documents'
      fullPath: '/admin/legal-documents'
      preLoaderRoute: typeof AdminLegalDocumentsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/legal': {
      id: '/admin/legal'
      path: '/legal'
      fullPath: '/admin/legal'
      preLoaderRoute: typeof AdminLegalRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/intelligence': {
      id: '/admin/intelligence'
      path: '/intelligence'
      fullPath: '/admin/intelligence'
      preLoaderRoute: typeof AdminIntelligenceRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/help-center': {
      id: '/admin/help-center'
      path: '/help-center'
      fullPath: '/admin/help-center'
      preLoaderRoute: typeof AdminHelpCenterRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/changelog': {
      id: '/admin/changelog'
      path: '/changelog'
      fullPath: '/admin/changelog'
      preLoaderRoute: typeof AdminChangelogRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/auth-diagnostics': {
      id: '/admin/auth-diagnostics'
      path: '/auth-diagnostics'
      fullPath: '/admin/auth-diagnostics'
      preLoaderRoute: typeof AdminAuthDiagnosticsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/analytics': {
      id: '/admin/analytics'
      path: '/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AdminAnalyticsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/account/support': {
      id: '/account/support'
      path: '/support'
      fullPath: '/account/support'
      preLoaderRoute: typeof AccountSupportRouteImport
      parentRoute: typeof AccountRoute
    }
    '/account/requests': {
      id: '/account/requests'
      path: '/requests'
      fullPath: '/account/requests'
      preLoaderRoute: typeof AccountRequestsRouteImport
      parentRoute: typeof AccountRoute
    }
    '/admin/legal/privacy': {
      id: '/admin/legal/privacy'
      path: '/privacy'
      fullPath: '/admin/legal/privacy'
      preLoaderRoute: typeof AdminLegalPrivacyRouteImport
      parentRoute: typeof AdminLegalRoute
    }
    '/account/requests/$id': {
      id: '/account/requests/$id'
      path: '/$id'
      fullPath: '/account/requests/$id'
      preLoaderRoute: typeof AccountRequestsIdRouteImport
      parentRoute: typeof AccountRequestsRoute
    }
  }
}

interface AccountRequestsRouteChildren {
  AccountRequestsIdRoute: typeof AccountRequestsIdRoute
}

const AccountRequestsRouteChildren: AccountRequestsRouteChildren = {
  AccountRequestsIdRoute: AccountRequestsIdRoute,
}

const AccountRequestsRouteWithChildren = AccountRequestsRoute._addFileChildren(
  AccountRequestsRouteChildren,
)

interface AccountRouteChildren {
  AccountRequestsRoute: typeof AccountRequestsRouteWithChildren
  AccountSupportRoute: typeof AccountSupportRoute
}

const AccountRouteChildren: AccountRouteChildren = {
  AccountRequestsRoute: AccountRequestsRouteWithChildren,
  AccountSupportRoute: AccountSupportRoute,
}

const AccountRouteWithChildren =
  AccountRoute._addFileChildren(AccountRouteChildren)

interface AdminLegalRouteChildren {
  AdminLegalPrivacyRoute: typeof AdminLegalPrivacyRoute
}

const AdminLegalRouteChildren: AdminLegalRouteChildren = {
  AdminLegalPrivacyRoute: AdminLegalPrivacyRoute,
}

const AdminLegalRouteWithChildren = AdminLegalRoute._addFileChildren(
  AdminLegalRouteChildren,
)

interface AdminRouteChildren {
  AdminAnalyticsRoute: typeof AdminAnalyticsRoute
  AdminAuthDiagnosticsRoute: typeof AdminAuthDiagnosticsRoute
  AdminChangelogRoute: typeof AdminChangelogRoute
  AdminHelpCenterRoute: typeof AdminHelpCenterRoute
  AdminIntelligenceRoute: typeof AdminIntelligenceRoute
  AdminLegalRoute: typeof AdminLegalRouteWithChildren
  AdminLegalDocumentsRoute: typeof AdminLegalDocumentsRoute
  AdminMarketIntelligenceRoute: typeof AdminMarketIntelligenceRoute
  AdminMonitoringRoute: typeof AdminMonitoringRoute
  AdminPerformanceRoute: typeof AdminPerformanceRoute
  AdminPublicStacksRoute: typeof AdminPublicStacksRoute
  AdminRevenueRoute: typeof AdminRevenueRoute
  AdminSupportRoute: typeof AdminSupportRoute
  AdminSupportCenterRoute: typeof AdminSupportCenterRoute
  AdminToolsRoute: typeof AdminToolsRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAnalyticsRoute: AdminAnalyticsRoute,
  AdminAuthDiagnosticsRoute: AdminAuthDiagnosticsRoute,
  AdminChangelogRoute: AdminChangelogRoute,
  AdminHelpCenterRoute: AdminHelpCenterRoute,
  AdminIntelligenceRoute: AdminIntelligenceRoute,
  AdminLegalRoute: AdminLegalRouteWithChildren,
  AdminLegalDocumentsRoute: AdminLegalDocumentsRoute,
  AdminMarketIntelligenceRoute: AdminMarketIntelligenceRoute,
  AdminMonitoringRoute: AdminMonitoringRoute,
  AdminPerformanceRoute: AdminPerformanceRoute,
  AdminPublicStacksRoute: AdminPublicStacksRoute,
  AdminRevenueRoute: AdminRevenueRoute,
  AdminSupportRoute: AdminSupportRoute,
  AdminSupportCenterRoute: AdminSupportCenterRoute,
  AdminToolsRoute: AdminToolsRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AccountRoute: AccountRouteWithChildren,
  AdminRoute: AdminRouteWithChildren,
  AgentsRoute: AgentsRoute,
  AppBuildersRoute: AppBuildersRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  BillingRoute: BillingRoute,
  CalculatorRoute: CalculatorRoute,
  CompareRoute: CompareRoute,
  FeedbackRoute: FeedbackRoute,
  FinderRoute: FinderRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  HelpRoute: HelpRoute,
  LoginRoute: LoginRoute,
  NewsRoute: NewsRoute,
  OnboardingRoute: OnboardingRoute,
  ProfileRoute: ProfileRoute,
  PromptsRoute: PromptsRoute,
  RankingsRoute: RankingsRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SettingsRoute: SettingsRoute,
  SignupRoute: SignupRoute,
  UnsubscribeRoute: UnsubscribeRoute,
  VerifyEmailRoute: VerifyEmailRoute,
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
  AuthVerifyEmailRoute: AuthVerifyEmailRoute,
  BlogSlugRoute: BlogSlugRoute,
  LegalTypeRoute: LegalTypeRoute,
  LegalDisclaimerRoute: LegalDisclaimerRoute,
  LegalPrivacyRoute: LegalPrivacyRoute,
  LegalTermsRoute: LegalTermsRoute,
  RefCodeRoute: RefCodeRoute,
  StacksIdRoute: StacksIdRoute,
  LegalIndexRoute: LegalIndexRoute,
  StacksIndexRoute: StacksIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
